<div class="content last ui-widget-content">
	<div class="content-full">
		<div style="width: 98%;padding-left: 5px;">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<div class="cms_table">
				<?php if ($this->Obj['isupdate'] == 0){?>
						<h2> Thêm mới kỳ thi</h2>
						<?php }?>
				<?php if ($this->Obj['isupdate'] == 1){?>
						<h2> Chỉnh sửa thông tin kỳ thi</h2>
						<?php }?>
				<form action="<?php echo BASE_URL; ?>/<?php echo $this->controller;?>/<?php echo $this->action;?>"	method="POST" name="quiz-form" id="">
					<input type="hidden" name="id" value="<?php echo $this->Obj['id'] ;?>">		
					<input type="hidden" name="isupdate" value="<?php echo $this->Obj['isupdate'];?>"/>			
					<table cellpadding="0" cellspacing="0">
						<tr><td class="label">
								Tên kỳ thi:
								</td><td class="field_container"><input type="text"  name="full_name" style="width: 300px "   value="<?php  echo $this->Obj['full_name']; ?>" >
						</td></tr>
						<tr><td class="label">
								Tên viết tắt:
								</td><td class="field_container"><input type="text" name="short_name"  style="width: 300px "   value="<?php  echo $this->Obj['short_name']; ?>" >
						</td></tr>
						<tr><td class="label">
								Kỳ thi thuộc khóa học: 
								</td><td class="field_container"><?php echo $this->SltCourse("course_id", $this->Obj['course_id'],1); ?>
						</td></tr>
						<tr><td colspan="3">
								<p>Mô tả chung cho kỳ thi:
								<textarea class="exam-summary-short-editor" name="summary" rows="3" cols="20"><?php  echo $this->Obj['summary']; ?></textarea>
								</p>
						</td></tr>
						<tr><td class="label">
								Mở kỳ thi:
								</td><td class="field_container"> <input type="checkbox" name="hidden" <?php if($this->Obj['hidden']=='on') echo "checked='checked'"; ?> >
						</td></tr>
						<tr><td colspan="3">
								<p>
									<label>Ghi chú:</label>
									<textarea class="exam-note-short-editor" name="note" rows="3" cols="20"><?php  echo $this->Obj['note']; ?></textarea>
								</p>
						</td></tr>
						<tr><td colspan="5"  style="font-size: 12px; color: white; font-family: tahoma;"  >
							<p align="center">
								<input  type="submit" value="Đồng ý" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">&nbsp;&nbsp;&nbsp;&nbsp;
								<input  type="button" value="Hủy bỏ" onclick="window.location='<?php echo  BASE_URL.'/exam';  ?>'" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">
							</p>
						</td></tr>
						
					</table>		
				</form>
				<!--  -->
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
			$(document).ready(function(){
				initEditorByClassShotcut("exam-summary-short-editor",500,false,true)
				initEditorByClassShotcut("exam-note-short-editor",500,false,true)
			});
</script>			
