<?php echo $this->doctype(); ?>
<html>
<head>
	<?php  echo  $this->headMeta(); ?>
	<?php  echo  $this->headTitle(); ?>
	<?php  echo  $this->headLink(); ?>
	<?php  echo  $this->jQuery(); ?>	
	<script type="text/javascript" src="<?php echo BASE_URL;?>/js/controller/question/add_ques_in_menu.js"></script>
	<link type="text/css" rel="stylesheet" href="<?php echo BASE_URL;?>/css/controller/question/add_ques_in_menu.css">
</head>
<body>
<?php 
		$auth = Zend_Auth::getInstance();
		if ($auth->hasIdentity()){
  			$userhaslogin = $auth->getStorage()->read();  	
  			
?>

<input type="hidden" name="BASE_URL" id="BASE_URL" value="<?php echo BASE_URL;?>">
<div class="teacher_main_content">
	<div class="teacher_banner">
		<span class="teacher-banner-left">	
		</span>
		<span class="teacher-banner-right">
			<?php echo $this->render("header.phtml");?>	
		</span>	
	</div>	
	<div class="teacher_head_nav">
		<ul>
			<li>
				<a href="<?php echo BASE_URL;?>/index" class="<?php
					if($this->controllerName ==  "index" && $this->actionName =="index") 
						echo "linkNavActive";
					else
						echo "linkNav";
					
				 ?>">Trang chủ</a>
			</li>				
		
			<li>
				<a class="<?php
					if($this->controllerName ==  "pagestudent" && $this->actionName =="editinfo") 
						echo "linkNavActive";
					else
						echo "linkNav";
					
				 ?>" href="<?php echo BASE_URL;?>/pagestudent/editinfo/user_id/<?php echo $userhaslogin->id ?>" class="">Tài khoản</a>
			</li>
			<li>
				<a class="<?php
					if($this->controllerName ==  "comment" && $this->actionName =="index") 
						echo "linkNavActive";
					else
						echo "linkNav";
					
				 ?>" href="<?php echo BASE_URL;?>/comment" class="">Trao đổi</a>
			</li>				
			<li>
				<a class="<?php
					if($this->controllerName ==  "index" && $this->actionName =="intro") 
						echo "linkNavActive";
					else
						echo "linkNav";
					
				 ?>" href="<?php echo BASE_URL;?>/index/intro" class="">Giới thiệu</a>
			</li>				
			
							
			<li>
				<a class="linkNav" href="<?php echo BASE_URL;?>/auth/logout" class="">Đăng xuất</a>
			</li>								
		</ul>
	</div>	
		<script type="text/javascript">
			$(document).ready(function(){
				if (screen.width<=1030) {
					$(".countdown-fix-position").css({'float' : 'left','padding-left' : '650px'});	 
				}
				if (screen.width > 1030) {
					$(".countdown-fix-position").css({'float' : 'left','padding-left' : '900px'});	 
				}
				
			});
		</script>

<table class="table-big">	
<tr>
	<td width="195px" class="col_left">
		<?php 
			echo $this->render("menu.phtml");
		?>
	</td>
	<td class="col_right">
		<?php if($this->hasClock==true){
				//echo '<div class="countdown-fix-position" style="float: left; padding-left: 650px;">';
				echo '<div class="countdown-fix-position">';
				  echo $this->countDownTimer($this->data['obj_test']['duration_test']);
				echo '</div>';
		}?>
		
		<?php  echo  $this->layout()->content ?>
	</td>
</tr>
</table>
</div>
<?php }else{
		header ("Location: ".BASE_URL."/auth/login");
} ?>
<?php echo $this->render("footer.phtml");?>
</body>
</html>
