<?php echo $this->doctype(); ?>
<html>
<head>
	<?php  echo  $this->headMeta(); ?>
	<?php  echo  $this->headTitle(); ?>
	<?php  echo  $this->headLink(); ?>
	<?php  echo  $this->jQuery(); ?>	
</head>
<body>
        <?php /*
	<div class="teacher_head_nav">
		<ul>
			<li>
				<a href="<?php echo BASE_URL;?>/index" class="<?php
					if($this->controllerName ==  "index" && $this->actionName =="index") 
						echo "linkNavActive";
					else
						echo "linkNav";
					
				 ?>">Trang chủ</a>
			</li>				
		
			<li>
				<a class="<?php
					if($this->controllerName ==  "pagestudent" && $this->actionName =="editinfo") 
						echo "linkNavActive";
					else
						echo "linkNav";
					
				 ?>" href="<?php echo BASE_URL;?>/pagestudent/editinfo/user_id/<?php echo $userhaslogin->id ?>" class="">Tài khoản</a>
			</li>	
			<li>
				<a class="<?php
					if($this->controllerName ==  "comment" && $this->actionName =="index") 
						echo "linkNavActive";
					else
						echo "linkNav";
					
				 ?>" href="<?php echo BASE_URL;?>/comment" class="">Trao đổi</a>
			</li>				
			<li>
				<a class="<?php
					if($this->controllerName ==  "index" && $this->actionName =="intro") 
						echo "linkNavActive";
					else
						echo "linkNav";
					
				 ?>" href="<?php echo BASE_URL;?>/index/intro" class="">Giới thiệu</a>
			</li>				
			<li>
				<a class="linkNav" href="<?php echo BASE_URL;?>/auth/logout" class="">Đăng xuất</a>
			</li>								
		</ul>
	</div>	
	*/ ?>
	
<input type="hidden" name="BASE_URL" id="BASE_URL" value="<?php echo BASE_URL;?>">
		<?php  echo  $this->layout()->content ?>	
</body>
</html>
