<?php if(count($this->arrSubjectId)>0 || $this->userhaslogin_groupID==5){ ?>		
		<div id="rightCol" >				
				<div class="name-page-cms">	Quản lý ngân hàng câu hỏi
				</div>
		</div>
		<div id="contentArea">				
			<!-- CMS -->
			<input type="hidden" id="CMS_SERVERSIDE" value="<?php echo BASE_URL;?>/question/serverside">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<div class="fi-question-filter">
			<fieldset style="width: 800px">
				<legend>Bộ lọc câu hỏi</legend>
				<dl>
					<table class="table-filter-question">
						<tr>
							<td class="left">Môn học:</td>
							<td class="right">
								<?php echo $this->SltSubject("subject_id", $this->subject_id,$this->arrSubjectId); ?>
								<script type="text/javascript">
									$(document).ready(function(){
										$("#subject_id").change(function(){
											var subject_id = $(this).val();
											$.ajax({
						    					   type: "POST",
						    					   url: $("#BASE_URL").val()+"/subject/getchapter/token/"+fnGenToken(),
						    					   data: "id="+subject_id,
						    					   dataType: "json",
						    					   success: function(data){
						    						 if(data['success']==true){
						    						 	$(".ajax_change_chapter_subject_id").html(data["view"]);
						    						 }
						    						 else
						    							 alert("Có lỗi: "+data['error']); 
						    					   }
						    					 });
										});
									});
								</script>
							</td>
						</tr>
						<tr>
							<td class="left">Chủ đề:</td>
							<td colspan="2" class="right">
								<span class="ajax_change_chapter_subject_id">
									<?php echo $this->SltChapterSubject("chapter_subject_id", $this->chapter_subject_id); ?>
								</span>
							</td>
						</tr>
						<tr>
							<td class="left">Loại câu hỏi:</td>
							<td colspan="2" class="right">
								<span class="ajax_change_type_question">
									<?php echo $this->SltTypeQuestion("SltTypeQuestion", $this->SltTypeQuestion); ?>
								</span>
							</td>
						</tr>
						
						<tr>
							<td class="left">Hiện tất cả các câu hỏi của ngân hàng:</td>
							<td colspan="2" class="right">
									<input type="checkbox" name="chkShowAllBankQuestion" class="chkShowAllBankQuestion">
							</td>
						</tr>
						
						<tr>
							<td style="text-align: center;">
								<input type="button" id="filter" value="&nbsp;&nbsp;Lọc&nbsp;&nbsp;" class="button" onclick="fnCustomFilter();"> 
							</td>
							<td>&nbsp;</td>
						</tr>
					</table>
				</dl>
			</fieldset>
			</div>
			<?php echo $this->table("table_question",$this->cols_view_title,"question");?>
			<script language="javascript">
				$(".chkShowAllBankQuestion").change(function(){
					fnCustomFilter();
				});
			
				function fnCustomFilter(){
					// gọi lại serverside sau khi search
					oTable.fnDraw();
				}
				$(document).ready(function(){
					InitJqueryDataTable("#table_question",[
															{
																"name" : "subject_id",
																"value" : function(){
																	return $("#subject_id").val();
																}
															},
															{
																"name" : "chapter_subject_id",
																"value" : function(){
																	return $("#chapter_subject_id").val();
																}
															},
															{
																"name" : "SltTypeQuestion",
																"value" : function(){
																	return $("#SltTypeQuestion").val();
																}
															},															
															{
																"name" : "chkShowAllBankQuestion",
																"value" : function(){
																	if($(".chkShowAllBankQuestion").attr("checked")==true)
																		return 1;
																	else return 0;
																}
															}																																									
														  ]);
				// Không cho search cột loại câu hỏi 														 
				$(".search-on-table").find("input[type='text']:eq(2)").hide();
				$(".search-on-table").find("input[type='text']:eq(3)").hide();
				$(".btn_delete_select").remove();
				
				});				
			</script>
			
			<!-- CMS -->
		</div>
			<!-- Dialog Add new question -->
			<div id="add-question-dialog-container" class="ui-corner-all ui-state-default">
				<h3>Chọn loại câu hỏi</h3>
				<div class="add-question-dialog-container-content ui-widget-content">
					<ul>
						<li><button name="<?php echo BASE_URL;?>/question/addmultichoice">Câu hỏi dạng : nhiều lựa chọn</button></li>
						<li><button name="<?php echo BASE_URL;?>/question/addtruefalse">Câu hỏi dạng : đúng sai</button></li>
						<li><button name="<?php echo BASE_URL;?>/question/addmatching">Câu hỏi dạng : ghép cặp</button></li>
						<li><button name="<?php echo BASE_URL;?>/question/addcompletion">Câu hỏi dạng : điền khuyết</button></li>
						<li><button name="<?php echo BASE_URL;?>/question/addessaytest">Câu hỏi dạng : tự luận</button></li>
						<li><button name="<?php echo BASE_URL;?>/question/addshortanswer">Câu hỏi dạng : trả lời ngắn</button></li>
					</ul>			
				</div>
				<div class="footer">
					<input type="button" value="Ðóng" id="btnCloseDialogAddNewQuestion">
				</div>
			</div>
			<!-- END Dialog Add new question -->			
			
<?php }else{ ?>
		<div class="name-page-cms">Bạn chưa được phân công giảng dạy môn học nào.</div>
		<div class="name-page-cms">Liên hệ với giáo vụ khoa để phân công giảng dạy cho bạn.</div>
		<script language="javascript">
			$(".flag-remove-link-add-question").remove();
		</script>
					
<?php } ?>			
