<?php if (count($this->arrError)>0) echo $this->error($this->arrError); 
else {
?>
<form action="<?php echo BASE_URL;?>/test/create" method="post" id="test-form">
<input type="hidden" name="isupdate" class=isupdate value="<?php echo $this->test['isupdate'];?>"/>
<input type="hidden" name="subject_id"  value="<?php echo $this->test['subject_id'];?>"/>

<!-- begin div tab big -->
	<div id="tabs" style="float:left;"> 
		<ul>
			<li><a href="#tabs-1">Thông tin cơ bản</a></li>
			<li><a href="#tabs-2">Chỉnh sửa câu hỏi</a></li>
			<li><a href="#tabs-3" id ="nav-tabs-3" title="<?php echo BASE_URL;?>/test/reviewtest/testID/<?php echo $this->test["id"]; ?>">Xem trước</a></li>
		</ul>
		<!-- begin div tab 1 -->
		<div id="tabs-1" class="container-tabs">
			<div class="cms_table">			
				<fieldset class="fieldset-setting-info-test">
					<legend >Thông tin chung</legend>
					<dl>
						<table>
							<tr>
								<td class="label"><span class="err-subject-highlight">
									Chọn môn học: </span>
										</td><td class="field_container">
										<?php echo $this->SltSubject("subject_id", $this->test['subject_id'],$this->arrSubjectId); ?>
										</td>
							</tr>
												
							<tr>
								<td class="label">Tiêu đề:
								</td>
								<td class="field_container"><input style="width: 350px" type="text" name="title" value="<?php echo $this->test["title"];?>" >
								</td>
							</tr>
							<tr>
								<td class="label">Cập nhật độ khó, phân cách:
								</td>
								<td class="field_container">
							    	<select name="auto_update_level">
							    		<option value="0" <?php if($this->Obj['auto_update_level']==0) echo "selected selected";?>>Không tự động</option>
							    		<option value="1" <?php if($this->Obj['auto_update_level']==1) echo "selected selected";?>>Tự động</option>
							    	</select>
								</td>
							</tr>
							<tr>
								<td class="label">Mở đề thi:
								</td>
								<td class="field_container">
									<input type="checkbox" name="hidden" <?php if($this->test['hidden']=='on') echo "checked"; ?> >
								</td>
							</tr>
							
							<tr>
								<td colspan="2" style="text-align: left; font-weight: bold;">Mô tả nội dung bài thi:
								</td>
							</tr>
							<tr>
								<td colspan="2">
									<textarea name="content" class="test-create-short-editor" id="test-create-short-editor" rows="15" cols="120"><?php echo $this->test["content"]; ?></textarea>									
								</td>
							</tr>
							<?php if( $this->test['isupdate'] == 1){ ?>
							<tr>
								<td class="label">Ngày tạo:
								</td>
								<td class="field_container">
								 	<input type="text" name="date_create" size="40" readonly="readonly" value="<?php  echo Zend_View_Helper_FormatDate::convertYmdToMdy($this->test['date_create']); ?>" >
								</td>
							</tr>
							<tr>
								<td class="label">Ngày chỉnh sửa gần nhất:
								</td>
								<td class="field_container">
									<input type="text" name="date_create" size="40" readonly="readonly" value="<?php  echo Zend_View_Helper_FormatDate::convertYmdToMdy($this->test['date_modify']); ?>" >
								</td>
							</tr>
							<?php } ?>
						</table>
					</dl>
				</fieldset>
				<fieldset class="fieldset-setting-info-test">
					<legend >Thời gian</legend>
					<dl>
						<ul class="list-setting-info-test">
							<li>
								<label class="test-setting-option-label-top">Thời gian làm bài (phút)</label>
								<input type="text" name="duration_test" onchange="validateNum(this);return false;" value="<?php echo $this->test["duration_test"];?>">
							</li>
						</ul>
					</dl>
				</fieldset>					
				<fieldset class="fieldset-setting-info-test">
					<legend  >Hiển thị</legend>
					<dl>
						<ul class="list-setting-info-test">
							<li>
								<label class="test-setting-option-label-top"> Số câu hỏi mỗi trang</label>
								<?php echo $this->SltTestPagination("question_perpage", $this->test["question_perpage"]); ?>
							</li>
							<li>
								<label class="test-setting-option-label-top">Xáo trộn vị trí câu hỏi</label>
								<select name="shuffle_question">								
									<option value="0" <?php  if($this->test["shuffle_question"]==0) echo 'selected = "selected" ';?> >Không</option>
									<option value="1" <?php  if($this->test["shuffle_question"]==1) echo 'selected = "selected" ';?> >Có</option>
								</select>
							</li>
							<li>
								<label class="test-setting-option-label-top">Xáo trộn vị trí câu trả lời</label>
								<select name="shuffle_answer">								
									<option value="0" <?php  if($this->test["shuffle_answer"]==0) echo 'selected = "selected" ';?> >Không</option>
									<option value="1" <?php  if($this->test["shuffle_answer"]==1) echo 'selected = "selected" ';?> >Có</option>
								</select>
							</li>
						</ul>
					</dl>
				</fieldset>	
				<fieldset class="fieldset-setting-info-test" style="display: none;">
					<legend >Số lần kiểm tra</legend>
					<dl>
						<ul class="list-setting-info-test">
							<li>
								<label class="test-setting-option-label-top">Số lần làm bài</label>
								<?php echo $this->SltAttemptAllow("attempts_allowed", $this->test["attempts_allowed"]); ?>
							</li>
						</ul>
					</dl>
				</fieldset>					
				<fieldset class="fieldset-setting-info-test">
					<legend >Điểm số</legend>
					<dl>
						<ul class="list-setting-info-test">
							<li style="display: none;">
								<label class="test-setting-option-label-top">Cách tính điểm</label>
								<select name="grade_method">								
									<option value="1" <?php  if($this->test["grade_method"]==1) echo 'selected = "selected" ';?> >Lần cao nhất</option>
									<option value="2" <?php  if($this->test["grade_method"]==2) echo 'selected = "selected" ';?> >Điểm trung bình</option>
									<option value="3" <?php  if($this->test["grade_method"]==3) echo 'selected = "selected" ';?> >Lần đầu tiên</option>
									<option value="4" <?php  if($this->test["grade_method"]==4) echo 'selected = "selected" ';?> >Lần cuối cùng</option>
								</select>
							</li>
							<li>
								<label class="test-setting-option-label-top">Số chữ số thập phân của điểm</label>
								<select name="decimal_digits_in_grades">								
									<option value="0" <?php  if($this->test["decimal_digits_in_grades"]==0) echo 'selected = "selected" ';?> >0</option>
									<option value="1" <?php  if($this->test["decimal_digits_in_grades"]==1) echo 'selected = "selected" ';?> >1</option>
									<option value="2" <?php  if($this->test["decimal_digits_in_grades"]==2) echo 'selected = "selected" ';?> >2</option>
									<option value="3" <?php  if($this->test["decimal_digits_in_grades"]==3) echo 'selected = "selected" ';?> >3</option>
								</select>
								
							</li>
						</ul>
					</dl>
				</fieldset>	
								
				<fieldset class="fieldset-setting-info-test">
					<legend>Tuỳ chọn xem lại</legend>
					<?php
						$review_after_test			= $this->test["review_after_test"];
						$review_while_test_open		= $this->test["review_while_test_open"];
						$review_after_test_close	= $this->test["review_after_test_close"]; 
					 ?>
					 <table>
					 	<tr>
					 		<td>
					 			<label style="font-weight: 600">Ngay sau lần kiểm tra </label>
					 		</td>
					 		<td>
					 			<label style="font-weight: 600">Sau này, khi đề thi chưa đóng  </label>
					 		</td>
					 		<td>
					 			<label style="font-weight: 600">Sau khi đề thi đóng </label>
					 		</td>
					 	</tr>
					 	<tr>
					 		<td>
					 			<span class="test-setting-option-review">
					 				<input type="checkbox" class="review_after_test" id="review_after_test_0"  <?php if($review_after_test[0]==1) echo 'checked="checked"'; ?> />
					 				<label class="test-setting-option-review-label">Xem đáp án đúng</label>
					 			</span>
					 			<span class="test-setting-option-review">
					 				<input type="checkbox" class="review_after_test" id="review_after_test_1" <?php if($review_after_test[1]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem giải thích </label>
					 			</span>
					 			<span class="test-setting-option-review" style="display: none">
					 				<input type="checkbox" class="review_after_test" id="review_after_test_2" <?php if($review_after_test[2]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem giải thích cho từng câu trả lời </label>
					 			</span>
					 			<span class="test-setting-option-review" style="display: none">
					 				<input type="checkbox" class="review_after_test" id="review_after_test_3" <?php if($review_after_test[3]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem điểm</label>
					 			</span>
					 		</td>
					 		<input type="hidden" name="review_after_test" id="review_after_test" value="<?php echo $review_after_test;?>">
					 		<td>
					 			<span class="test-setting-option-review">
					 				<input type="checkbox" class="review_while_test_open" id="review_while_test_open_0"  <?php if($review_while_test_open[0]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem đáp án đúng</label>
					 			</span>
					 			<span class="test-setting-option-review">
					 				<input type="checkbox" class="review_while_test_open" id="review_while_test_open_1"  <?php if($review_while_test_open[1]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem giải thích</label>
					 			</span>

					 			<span class="test-setting-option-review" style="display: none">
					 				<input type="checkbox" class="review_while_test_open" id="review_while_test_open_2"  <?php if($review_while_test_open[2]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem giải thích cho từng câu trả lời </label>
					 			</span>

					 			<span class="test-setting-option-review" style="display: none">
					 				<input type="checkbox" class="review_while_test_open" id="review_while_test_open_3"  <?php if($review_while_test_open[3]==1) echo 'checked="checked"'; ?> />
					 				<label class="test-setting-option-review-label">Xem điểm</label>
					 			</span>
					 			<input type="hidden" name="review_while_test_open" id="review_while_test_open" value="<?php echo $review_while_test_open;?>">
					 		</td>
					 		<td>
					 			<span class="test-setting-option-review">
					 				<input type="checkbox" class="review_after_test_close" id="review_after_test_close_0"  <?php if($review_after_test_close[0]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem đáp án đúng</label>
					 			</span>
					 			<span class="test-setting-option-review">
					 				<input type="checkbox" class="review_after_test_close" id="review_after_test_close_1"  <?php if($review_after_test_close[1]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem giải thích</label>
					 			</span>
					 			<span class="test-setting-option-review" style="display: none">
					 				<input type="checkbox" class="review_after_test_close" id="review_after_test_close_2"  <?php if($review_after_test_close[2]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem giải thích cho từng câu trả lời </label>
					 			</span>
					 			<span class="test-setting-option-review" style="display: none">
					 				<input type="checkbox" class="review_after_test_close" id="review_after_test_close_3"  <?php if($review_after_test_close[3]==1) echo 'checked="checked"'; ?>/>
					 				<label class="test-setting-option-review-label">Xem điểm</label>
					 			</span>
					 		</td>
					 		<input type="hidden" name="review_after_test_close" id="review_after_test_close" value="<?php echo $review_after_test_close;?>">
					 	</tr>					 	
					 </table>
				</fieldset>		
			</div>			
		</div>	
		<!-- end div tab 1 -->
		<!-- begin div tab 2 -->
		<div id="tabs-2" class="container-tabs">		
				<table>
					<tr>
						<td style="width: 50%">
						<div class="create-test">
						<?php
							$test = $this->test;
							$list_questionID = explode(',',$test["list_question"]);
							$list_score    = explode(',',$test["list_score"]);		
						?>
							<input type="hidden" name="id" class="id-of-test" value="<?php echo $test["id"];?>">
							<table class="table-test-list-question datatable" >
								<tr>
									<th colspan="2" class="table-edit-question-intest" scope="col">Chuyển
									</th>
									<th class="table-edit-question-intest" scope="col">#
									</th>
									<th class="table-edit-question-intest" align="left"> Tiêu đề câu hỏi
									</th>
									<th class="table-edit-question-intest" scope="col">Điểm
									</th>
									<th align="center" class="table-edit-question-intest" scope="col">Thao tác
									</th>
								</tr>							
							<tr><td colspan="10" height="10"></td> </tr>
							<?php
								if(!empty($list_questionID[0]))
								foreach($list_questionID as $key=>$list_questionIDItem){ 
							 ?>
								<tr>
									<td width="25">
										<a href="#" class="up-arrow"   onclick="fnUpArrow(this)">
										<img class="fugue fugue-arrow-090"  alt="Di chuyển lên" title="Di chuyển lên" src="<?php echo BASE_URL;?>/img/icons/space.gif"/>
										</a>
									</td>
									<td  width="25">
										<a href="#" class="down-arrow" onclick="fnDownArrow(this)">
										<img class="fugue fugue-arrow-270"  alt="Di chuyển xuống" title="Di chuyển xuống"  src="<?php echo BASE_URL;?>/img/icons/space.gif"/>
										</a>
									</td>
									<td style="text-align: center;"><span class="indexQuestion"><?php echo $key+1; ?></span></td>
									<td>
										<span class="test-has-question-<?php echo $list_questionIDItem;?>">
											<?php
												$models_question = new Default_Models_Question();
												$models_question->find("id",$list_questionIDItem);
												echo $models_question->getQuestion_title();					
											?>
										</span>
									</td>
									<td>
										<input type="hidden" class="questionIDofTest" name="list_question[]" value="<?php echo $list_questionIDItem;?>"/>
										<input type="text" maxlength="3" size="3" class="scoreOneQuestion scoreOneQuestion-<?php echo $list_questionIDItem;?>" name="list_score[]" onchange="validateNum(this);UpdateSumScoreOfTest(); return false;" value="<?php echo $list_score[$key];?>"/>
									</td>
									<td style="text-align: center;">
										<a class="view-icon"   href="<?php echo BASE_URL;?>/question/preview/id/<?php echo $list_questionIDItem;?>" onclick="viewClick(this.href); return false;"><img class="fugue fugue-eye" alt="Xem trước" src="<?php echo BASE_URL;?>/img/icons/space.gif"/></a>
										<a class="edit-icon-popup"   href="<?php echo BASE_URL;?>/question/edit/id/<?php echo $list_questionIDItem;?>" onclick="editPopup(this.href); return false;"><img class="fugue fugue-pencil" alt="Chỉnh sửa" src="<?php echo BASE_URL;?>/img/icons/space.gif"/></a>
										<a class="remove-icon" href="#" onclick="removeQuestionFromTest(this); return false;"><img class="fugue fugue-control-double"  alt="Xóa"       src="<?php echo BASE_URL;?>/img/icons/space.gif"/></a> 				
									</td>
								</tr>
							<?php } ?>
								<tr>
									<td colspan="4">
										Tổng số câu hỏi <span class="sumQuestionOfTest">0</span>
									</td>
									<td colspan="2">
										Tổng số điểm  <span class="sumScoreOfTest"></span>  
									</td>
									
								</tr>
							</table>
						</div>
						</td>
						<td style="width: 50%">		
							<div class="question-cms">
								<input type="hidden" id="CMS_SERVERSIDE" value="<?php echo BASE_URL;?>/question/serversidecreatetest">
								
								<fieldset>
									<legend>Bộ lọc câu hỏi</legend>
									<dl>
										<table>
											<tr>
												<td>Môn học:</td>
												<td>
													<?php echo $this->SltSubject("slt_searchBy_subject_id", $this->subject_id); ?>
													<script type="text/javascript">
														$(document).ready(function(){
															$("#slt_searchBy_subject_id").change(function(){
																var subject_id = $(this).val();
																$.ajax({
											    					   type: "POST",
											    					   url: $("#BASE_URL").val()+"/subject/getchapter/token/"+fnGenToken(),
											    					   data: "id="+subject_id,
											    					   dataType: "json",
											    					   success: function(data){
											    						 if(data['success']==true){
											    						 	$(".ajax_change_chapter_subject_id").html(data["view"]);
											    						 }
											    						 else
											    							 alert("Có lỗi: "+data['error']); 
											    					   }
											    					 });
															});
														});
													</script>
												</td>
											</tr>
											<tr>
												<td>Chủ đề:</td>
												<td colspan="2">
													<span class="ajax_change_chapter_subject_id">
														<?php echo $this->SltChapterSubject("chapter_subject_id", 0); ?>
													</span>
												</td>
											</tr>
											<tr>
												<td class="left">Loại câu hỏi:</td>
												<td colspan="2" class="right">
													<span class="ajax_change_type_question">
														<?php echo $this->SltTypeQuestion("SltTypeQuestion", $this->SltTypeQuestion); ?>
													</span>
												</td>
											</tr>
											
											<tr>
												<td>Hiện tất cả các câu hỏi của ngân hàng</td>
												<td colspan="2">
														<input type="checkbox" name="chkShowAllBankQuestion" class="chkShowAllBankQuestion">
												</td>
											</tr>
											
											<tr>
												<td style="text-align: center;">
													<input type="button" id="filter" value="&nbsp;&nbsp;Lọc&nbsp;&nbsp;" class="button" onclick="fnCustomFilter();"> 
												</td>
												<td>&nbsp;</td>
											</tr>
										</table>
									</dl>
								</fieldset>
			
									<?php echo $this->table("table_question_in_test",$this->cols_view_title,"question");?>
								<script language="javascript">
									$(".chkShowAllBankQuestion").change(function(){
										fnCustomFilter();
									});
									function fnCustomFilter(){
										// gọi lại serverside sau khi search
										oTable.fnDraw();
									}								
									$(document).ready(function(){
										InitJqueryDataTable("#table_question_in_test",[
																				{
																					"name" : "subject_id",
																					"value" : function(){
																						return $("#slt_searchBy_subject_id").val();
																					}
																				},
																				{
																					"name" : "chapter_subject_id",
																					"value" : function(){
																						return $("#chapter_subject_id").val();
																					}
																				},
																				{
																					"name" : "SltTypeQuestion",
																					"value" : function(){
																						return $("#SltTypeQuestion").val();
																					}
																				},
																				{
																					"name" : "chkShowAllBankQuestion",
																					"value" : function(){
																						if($(".chkShowAllBankQuestion").attr("checked")==true)
																							return 1;
																						else return 0;
																					}
																				}																																									
																																	
																			  ]);
										$(".btn_delete_select").remove();
									});				
								</script>								
								<!-- END CMS -->
								<!-- Dialog Add new question -->
								<div id="add-question-dialog-container" class="ui-corner-all ui-state-default">
									<h3>Chọn loại câu hỏi</h3>
									<div class="add-question-dialog-container-content ui-widget-content">
										<ul>
											<li><button name="<?php echo BASE_URL;?>/question/addmultichoice">Câu hỏi dạng : nhiều lựa chọn</button></li>
											<li><button name="<?php echo BASE_URL;?>/question/addtruefalse">Câu hỏi dạng : đúng sai</button></li>
											<li><button name="<?php echo BASE_URL;?>/question/addmatching">Câu hỏi dạng : ghép cặp</button></li>
											<li><button name="<?php echo BASE_URL;?>/question/addcompletion">Câu hỏi dạng : điền khuyết</button></li>
											<li><button name="<?php echo BASE_URL;?>/question/addessaytest">Câu hỏi dạng : tự luận</button></li>
											<li><button name="<?php echo BASE_URL;?>/question/addshortanswer">Câu hỏi dạng : trả lời ngắn</button></li>
										</ul>			
									</div>
									<div class="footer">
										<input type="button" value="Ðóng" id="btnCloseDialogAddNewQuestion">
									</div>
								</div>		
								<!-- END Dialog Add new question -->					
							</div>
						</td>
					</tr>
				</table>					
		</div>
		<!-- end div tab 2 -->
		<!-- begin div tab 3 -->
		
		<div id="tabs-3" style="text-align: left;" class="container-tabs">
			<iframe src="" width="968" height="600" scrolling="auto">
			</iframe>
		</div>
		<!-- end div tab 3 -->
		<a class="button mgt10" href="#" onclick="fnAjaxSubmitForm(); return false;" >Lưu lại</a>
	</div>	
	<!-- end div tab big -->
</form>
<?php } ?>
<script type="text/javascript" language="javascript">	
	$(document).ready(function(){
//            $("iframe").contents().find(".teacher_head_nav").remove();
		repairUpDownArrow();
		UpdateSumScoreOfTest();
		UpdateSumQuestionOfTest();
		$("#tabs").tabs({
			select: function(event, ui) {
					if(ui.tab.title){
							var src = ui.tab.title + "/token/"+fnGenToken();
							//alert(src); 				
			        		$(ui.tab.hash).find("iframe").attr("src",src);                                                
			        	}
			        return true;
			    }		
		});
		// Khởi tạo short editor
		initEditorByClassShotcut("test-create-short-editor",550,false,true); 
		<?php if($this->selectedTab =="generalTest") echo  '$("#tabs").tabs("select", 0);'; ?>
		<?php if($this->selectedTab =="editTest") 	 echo '$("#tabs").tabs("select", 1);'; ?>
		<?php if($this->selectedTab =="previewTest") echo '$("#tabs").tabs("select", 2);'; ?>
		
		
		$(".review_after_test").click(function(){
			var id    			  = $(this).attr("id")+ "";
			var index 			  = id.replace("review_after_test_", "")*1;
			var review_after_test = $("#review_after_test").val();
			if($(this).attr("checked"))
				review_after_test = review_after_test.substr(0,index) + "1" + review_after_test.substr(index+1);
			else
				review_after_test = review_after_test.substr(0,index) + "0" + review_after_test.substr(index+1);
			$("#review_after_test").val(review_after_test);
		});	
		
		
		$(".review_while_test_open").click(function(){
			var id    			  = $(this).attr("id")+ "";
			var index 			  = id.replace("review_while_test_open_", "")*1;
			var review_while_test_open = $("#review_while_test_open").val();
			if($(this).attr("checked"))
				review_while_test_open = review_while_test_open.substr(0,index) + "1" + review_while_test_open.substr(index+1);
			else
				review_while_test_open = review_while_test_open.substr(0,index) + "0" + review_while_test_open.substr(index+1);
			$("#review_while_test_open").val(review_while_test_open);
		});
		
		$(".review_after_test_close").click(function(){
			var id    			  = $(this).attr("id")+ "";
			var index 			  = id.replace("review_after_test_close_", "")*1;
			var review_after_test_close = $("#review_after_test_close").val();
			if($(this).attr("checked"))
				review_after_test_close = review_after_test_close.substr(0,index) + "1" + review_after_test_close.substr(index+1);
			else
				review_after_test_close = review_after_test_close.substr(0,index) + "0" + review_after_test_close.substr(index+1);
			$("#review_after_test_close").val(review_after_test_close);
		});	
			
	/*
		$(".click-review-test").click(function(){
			var test_id = $(".id-of-test").val();
			if(test_id.length==0) // cái này cần kiểm tra lại có phải khi nào id quăng xuống cũng rỗng ko
				alert("Trước khi xem trước bạn phải lưu bài thi ");
			else
			$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/test/reviewtest",
    					   data: "testID="+test_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
    						 	var textTemp = "test-has-question-"+question_id; 
    						 	$("span.test-has-question-"+question_id).html("asdasdhajksdh");
								UpdateSumScoreOfTest(); // Cập nhật lại tổng điểm của bài test trên giao diện --- không save vào database
								UpdateSumQuestionOfTest();	// Cập nhật lại tổng số câu hỏi của bài test trên giao diện --- không save vào database
    						 }
    						 else
    							 alert("Có lỗi "+data['error']); 
    					   }
    		});
		});
	*/	
		
	});
	// 
	function fnAjaxSubmitForm(){
		tinyMCE.triggerSave();
                        $(".cms_table").block({
                                message: '<span><b>Đang xử lý...</b></span>',                 
                        overlayCSS:  {  
                            '-webkit-border-radius': '3px', 
                            '-moz-border-radius':    '3px',	
                            'padding-bottom': '3px',
                            backgroundColor: '#fff'
                        }
                        });                  
		$.ajax({
    				type: "POST",
    				url: $("#test-form").attr("action"),
    				data: $("#test-form").serialize(),
    				dataType: "json",
    				success: function(data){
	    				if(data['success']==true){
									$(".id-of-test").val(data["id_last_insert_test"]);
									$(".isupdate").val(data["isupdate"]);
									$("#nav-tabs-3").attr("title",$("#BASE_URL").val()+"/test/reviewtest/testID/"+data["id_last_insert_test"]);
                                                                         
									//alert($("#nav-tabs-3").attr("title"));
									//location.href = $("#BASE_URL").val()+"/test/create/testID/"+data["id_last_insert_test"];
	    					//alert("Save Data Success" + data["id_last_insert_test"]);	    					
	    					alert("Lưu đề thi thành công");
	    				}else{
	    					if(data['error']=='subject_id_null'){
	    						$(".err-subject-highlight").css({'border' : '3px solid red','width' : '250px','height' : '50px'});
	    						$("#tabs").tabs("select", 0);
	    						$(window).scrollTop(30)
	    						alert("Có lỗi: chưa chọn môn học cho đề thi");
	    						//$(".teacher_main_content").scrollTop(30);
	    						
	    					}else
    							alert("Có lỗi "+data['error']);
	    				} 
                                        $(".cms_table").unblock();
    				}
				});		
	}
	
	/* da move ra file cms.js de dung duoc trong question cms va test cms
	// hàm cập nhật các question được edit khi ta soạn test
	function fnUpdateQuestion(question_id){
		alert(question_id);
		    			$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/question/getonequestion",
    					   data: "id="+question_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
    						 	var textTemp = "test-has-question-"+question_id; 
    						 	$("span.test-has-question-"+question_id).html(data["data"]["question_title"]);
    						 	$(".scoreOneQuestion-"+question_id).val(data["data"]["question_score"]);
    						 	//question_score
								UpdateSumScoreOfTest(); // Cập nhật lại tổng điểm của bài test trên giao diện --- không save vào database
								UpdateSumQuestionOfTest();	// Cập nhật lại tổng số câu hỏi của bài test trên giao diện --- không save vào database
    						 }
    						 else
    							 alert("Có lỗi: "+data['error']); 
    					   }
    					 });
	}
	*/
	//  hàm di chuyển vị trí (lên xuống)của question trên bài test, sau khi di chuyển xong thì cập nhật lại số thứ tự của question
	function fnDownArrow(this_){
			var this_tr = $(this_).parent("td").parent("tr");
			var next_tr = this_tr.next();
			next_tr.after(this_tr);
			repairUpDownArrow();
			repairIndexQuestion();
			return false;	
	}
	//  hàm di chuyển vị trí (lên xuống)của question trên bài test, sau khi di chuyển xong thì cập nhật lại số thứ tự của question
	function fnUpArrow(this_){
		// this_tr: tìm cái <tr> hiện tại
		var this_tr = $(this_).parent("td").parent("tr");
		var prev_tr = this_tr.prev();
		// Chèn cái <tr> prev_tr lên trước cái this_tr
		prev_tr.before(this_tr);
		repairUpDownArrow();
		repairIndexQuestion();
		return false;			
	}
	
	// Hàm khi add câu hỏi từ ngân hàng qua bài test, ta thêm 1 <tr> sang table test
	function addToTest(question_id){
		if (validateQuesIDBeforeAddToTest(question_id))
		{
    				$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/question/getonequestion",
    					   data: "id="+question_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
    						  /* $(".table-test-list-question").find("tr :first").remove();*/  
    						 	var html_tr = '';
									html_tr += '<tr>';
									html_tr += '<td>';
											html_tr += '<a href="#" class="up-arrow"   onclick="fnUpArrow(this)">';
											html_tr += '<img class="fugue fugue-arrow-090"  alt="Di chuyển lên" title="Di chuyển lên" src="<?php echo BASE_URL;?>/img/icons/space.gif"/></a>';
										html_tr += '</td>';
										html_tr += '<td>';
											html_tr += '<a href="#" class="down-arrow" onclick="fnDownArrow(this)"><img class="fugue fugue-arrow-270"  alt="Di chuyển xuống" title="Di chuyển xuống"  src="<?php echo BASE_URL;?>/img/icons/space.gif"/></a>';
										html_tr += '</td>';
										html_tr += '<td><span class="indexQuestion"></span></td>';
										html_tr += '<td><span class="test-has-question-'+question_id+'">';
										html_tr += data["data"]["question_title"];
										html_tr += '</span></td>';
										html_tr += '<td>';
											html_tr += '<input type="hidden"  class="questionIDofTest" name="list_question[]" value="'+question_id+'"/>';
											html_tr += '<input type="text" maxlength="3" size="3" class="scoreOneQuestion scoreOneQuestion-'+question_id+'" name="list_score[]" onchange="validateNum(this);UpdateSumScoreOfTest(); return false;"  value="'+data["data"]["question_score"]+'"/>';
										html_tr += '</td>';
										html_tr += '<td style="text-align: center;">';
											html_tr += '<a class="view-icon"   href="'+$("#BASE_URL").val()+'/question/preview/id/'+question_id+'" onclick="viewClick(this.href); return false;"><img class="fugue fugue-eye" alt="" src="'+$("#BASE_URL").val()+'/img/icons/space.gif"/></a>';
											html_tr += '&nbsp;<a class="edit-icon-popup"   href="'+$("#BASE_URL").val()+'/question/edit/id/'+question_id+'" onclick="editPopup(this.href); return false;"><img class="fugue fugue-pencil" alt="Chỉnh sửa" src="'+$("#BASE_URL").val()+'/img/icons/space.gif"/></a>';
											html_tr += '&nbsp;<a class="remove-icon" href="#" onclick="removeQuestionFromTest(this); return false;" ><img class="fugue fugue-control-double"  alt="Xóa"       src="'+$("#BASE_URL").val()+'/img/icons/space.gif"/></a>'; 				
										html_tr += '</td>';
									html_tr += '</tr>';		
    								$(".table-test-list-question").find("tr:eq(1)").after(html_tr); 
									repairUpDownArrow(); // Cập nhật lại vị trí 2 nút UP DOWN của câu hỏi
									repairIndexQuestion(); // Cập nhật lại số thứ tự của câu hỏi   	
									UpdateSumScoreOfTest(); // Cập nhật lại tổng điểm của bài test trên giao diện --- không save vào database
									UpdateSumQuestionOfTest();	// Cập nhật lại tổng số câu hỏi của bài test trên giao diện --- không save vào database
    						 }
    						 else
    							 alert("Có lỗi "+data['error']); 
    					   }
    					 });
    	}
	}
	
	// xóa một câu hỏi từ bên test
	function removeQuestionFromTest(this_){
		var this_tr = $(this_).parent("td").parent("tr");
		// xóa cái <tr> hiện tại
		this_tr.remove();
		repairUpDownArrow();
		repairIndexQuestion();
		UpdateSumScoreOfTest();
		UpdateSumQuestionOfTest();
	}
	
	// Chỉnh sửa lại 2 dòng đầu và cuối của bài test 
	function repairUpDownArrow(){
		$(".up-arrow").show();
		$(".down-arrow").show();
		$(".up-arrow:first").hide();
		$(".down-arrow:last").hide();
	}
	// Chỉnh sửa lại số thứ tự câu hỏi trên bài test
	function repairIndexQuestion(){
		var count = 0;
		var sumScore = 0;
		$(".indexQuestion").each(function(){
			count++;
			$(this).html(count+"");
		});
	}
	
	// Cập nhật lại tổng số điểm của bài test tương ứng với những câu hỏi hiện có của bài test
	function UpdateSumScoreOfTest(){
		var sumScore = 0;
		var html="";
		$(".scoreOneQuestion").each(function(){
			sumScore +=  (($(this).val())*1);
		});
		sumScore = sumScore+'';
		sumScore = sumScore.substring(0,5)
		html +='<span class="sumScoreOfTest">'+ sumScore +'</span>  '; 
		$(".sumScoreOfTest").html(html);
	}
	
	// Cập nhật lại tổng số câu hỏi của bài test trên giao diện 
	function UpdateSumQuestionOfTest(){
		var sum = 0;
		var html="";
		$(".indexQuestion").each(function(){
			sum+=1;
		});
		html +='<span class="sumQuestionOfTest">'+ sum +'</span>  '; 
		$(".sumQuestionOfTest").html(html);
	}
	
	// Kiểm tra id của câu hỏi khi add từ bên ngân hàng qua bên test, nếu có rồi thì không add vào nữa
	function validateQuesIDBeforeAddToTest(question_id_in_bank){
		var flag = 0;
		$(".questionIDofTest").each(function(){
				if (question_id_in_bank == ($(this).val()*1)){
					flag = 1; 
					return false; // to break each(function) 
				}
		});
		if (flag == 1) return false ; // return of validateQuesIDBeforeAddToTest
		return true;
	}
	
</script>

