		<div id="rightCol" >	
				<div class="name-page-cms">	Quản lý đề thi
				</div>
		</div>
<!-- CMS -->
<input type="hidden" id="CMS_SERVERSIDE" value="<?php echo BASE_URL;?>/test/serverside">
<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
<?php echo $this->table("table_test",$this->cols_view_title,"test");?>
<script language="javascript">
	$(document).ready(function(){
		InitJqueryDataTable("#table_test","");
	});				
</script>

<div id="view-container" class="ui-corner-all ui-widget-content">
</div>
<!-- CMS -->
