<form action="<?php echo BASE_URL;?>/test/onlypreview" method="post" id="teacher-onlyreview-test-form">

<input type="hidden" name="testID"  value="<?php echo $this->data["testID"];?>">

<script type="text/javascript" language="javascript">
<!--
$(document).ready(function(){
	$("#time-countdown").countdown('resume');
	$(".question-container-div").hide()
	$(".separator-question-test").hide()
	var question_per_page = $(".question_per_page").val();
	showPage(0,question_per_page);
	$(".focus-page-test").eq(0).addClass("focus-page-test-active");
});
function focusPage(up_or_down,currentPage){
	page_obj  = $(".focus-page-test-"+up_or_down);
	page_obj.removeClass("focus-page-test-active");
	page_obj.eq(currentPage).addClass("focus-page-test-active");
}
function showPage(currentPage, questionPerpage)
{
	focusPage(1,currentPage);
	focusPage(2,currentPage);
	$(".question-container-div").hide()
	$(".separator-question-test").hide()
	var start  	= currentPage*questionPerpage;
	var end		= start+questionPerpage;
	for(i=start; i< end; i++){
		$(".separator-question-test").eq(i).show();
		$(".question-container-div").eq(i).show();
	}
}

function endTest() {
	$("#teacher-onlyreview-test-form").submit();
}
function endTestConfirm() {
	if(confirm("Bạn chắc chắn muốn nộp bài?")==true)
		$("#teacher-onlyreview-test-form").submit();
}
//-->
</script>

<?php
	if(!empty($this->data["testID"])){
			$list_questionID 	= $this->data['question_id'];// danh sách id của câu hỏi
			$list_score    		= $this->data['question_score'];// điểm làm bài của user
			$questionPerPage	= $this->data["question_perpage"];
                        $answer_of_user 	= isset($this->data['question'])?$this->data['question']:array(); // các câu trả lời của user
			$list_score_in_test_table	= $this->data["list_score_in_test_table"];// Điểm của câu hỏi được set trong bài test
			$questionPerPage 	= $questionPerPage==0? 1:$questionPerPage;
			$totalQuestion		= count($list_questionID);
			$totalPage			= (int)($totalQuestion/$questionPerPage);
			$totalPage			= $totalQuestion%$questionPerPage==0?$totalPage:($totalPage+1) ;
?>

<div class="title_test_theme-1">
	<p class="title_test_theme">
		<?php echo  $this->data['obj_test']['title'];?>
	</p>
<table class="table-student-reviewtest-statistic">
	<tr>
		<td class="left">Bài thi có:
		</td>
		<td class="right"><?php echo $totalPage." trang"; ?> 
		</td>
	</tr>
	<tr>
		<td class="left" colspan="2">
			<?php echo  $this->data['obj_test']['content'];?>
		</td>
	</tr>
	
	<tr>
		<td class="left" colspan="2">
			Câu hỏi dạng tự luận sẽ được giảng viên chấm điểm sau khi nộp bài.
		</td>
	</tr>
</table>		
</div>
<?php		
			$link = "<div class='page_review_test'><font style='font-size: 16px; font-weight: bold; '>Trang: </font> ";
				for($i=0;$i<$totalPage;$i++)
					$link .= "&nbsp;<a href='#' onclick='showPage($i,$questionPerPage); return false;'><span class='focus-page-test-1'> ".($i+1)."</span></a> &nbsp;&nbsp;";
			$link .="</div>";
			echo $link;
			if(!empty($list_questionID[0])){		
					foreach($list_questionID as $key=>$list_questionIDItem){
                                                $answer_of_user_temp = isset($answer_of_user[$list_questionIDItem])?$answer_of_user[$list_questionIDItem]:"";
                                                $list_score_temp = isset($list_score[$key])?$list_score[$key]:1;
							// Begin Lấy đường dẫn tuyệt đối cho hình ảnh
							$HTML = $this->viewQuestion($this->data["testID"],
                                                                trim($list_questionIDItem),
                                                                "Câu ".($key+1)." : ",
                                                                $answer_of_user_temp,
                                                                $this->review_test,
                                                                $this->view_corect,
                                                                $this->view_feedback,
                                                                $this->view_send_result,
                                                                $list_score_temp, 
                                                                $list_score_in_test_table[$key]);
							$HTML = Zend_View_Helper_FormatDate::_tinyMce_get_absolute_path_image("../../../media/images/tinymce","http://".$_SERVER['SERVER_NAME'].BASE_URL."/media/images/tinymce" ,$HTML);
							// End lấy đường dẫn tuyệt đối cho hình ảnh
							echo  $HTML;
						
							echo "<span class='separator-question-test'><hr/></span>";
					}
			$link = "<div class='page_review_test'><font style='font-size: 16px; font-weight: bold; '>Trang: </font> ";
			for($i=0;$i<$totalPage;$i++)
				$link .= "&nbsp;<a href='#' onclick='showPage($i,$questionPerPage); return false;'><span class='focus-page-test-2'> ".($i+1)."</span></a> &nbsp;&nbsp;";			
				$link .="</div>";
			echo $link;
			}
?>			
<p align="center">
			<input type="hidden" class="question_per_page" value="<?php echo $questionPerPage; ?>">
		<a  class="all-bt-do-test" href="#" onclick="endTestConfirm(); return false;">Nộp bài </a>&nbsp;&nbsp;&nbsp;&nbsp;
	 	<a  class="all-bt-do-test" href="#" onclick="window.close()">Đóng lại </a>
</p>
<?php  		 
	
	}else{ 
			echo "<p> Không tồn tại đề thi này.</p>";
 	} ?>

</form>
<hr/>

<style>
</style>