<?php 
			// Begin Lấy đường dẫn tuyệt đối cho hình ảnh
		$HTML = $this->viewQuestionTestOne($this->test_id,trim($this->question_id),$this->question_title_order ,$this->answer_of_user,$this->review_test,$this->view_corect,$this->view_feedback,$this->view_send_result,$this->question_score, $this->score_of_question);
		$HTML = Zend_View_Helper_FormatDate::_tinyMce_get_absolute_path_image("../../../media/images/tinymce","http://".$_SERVER['SERVER_NAME'].BASE_URL."/media/images/tinymce" ,$HTML);
		// End lấy đường dẫn tuyệt đối cho hình ảnh
		echo  $HTML;
		
?>		
<script type="text/javascript" language="javascript">	
function getCT(){
	alert(1);
	alert(tinyMCE.get("testMCE").getContent());
}
$(document).ready(function(){
		initShortEditorByClassTestOneQues("short-editor-essay-testone",400,false,true);
		/*
		$("#short-editor-essay-testone").before("<textarea id='testMCE'>abcd</textarea>");
		initEditorById("testMCE",400,false,true);
		setTimeout("getCT()",3000);
		tinyMCE.triggerSave();
				
		var id = "short-editor-essay-testone-" + fnGenToken();
		$("#short-editor-essay-testone").attr("id",id);
		//$("#short-editor-essay-testone").remove();
		tinyMCE.remove("short-editor-essay-testone");
		
		//alert(tinyMCE.get("short-editor").getContent());	
		 
		//tinyMCE.get("short-editor-essay-testone").execCommand('mceSetContent',false, '<p>some text<table></table></p>' );
		
		//tinyMCE.triggerSave();
		/*
		tinyMCE.execCommand('mceFocus', true, "short-editor-essay-testone");
		tinyMCE.activeEditor.setContent('<span>some</span> html');
		alert(tinyMCE.get("short-editor-essay-testone").getContent());
		*/
					
});

		
		
					
</script>
