<div id="blueBar"></div>
<div id="globalContainer">
	<?php echo $this->render("navigation.phtml");?>
	<div id="content" class="hasLeftCol">
		<div id="contentCol" class="hasRightCol">
			<div id="rightCol" >
				<div class="name-page-cms">	Thống kê
				</div>
			</div>
			<div id="contentArea">
				<div class="index-statisticsystem-p">
					<p>
						<a class="" href="<?php echo BASE_URL;?>/statisticsystem/statistictest">
						<img class="fugue fugue-tables--arrow" alt="" src="<?php echo BASE_URL;?>/img/icons/space.gif"/>Đề thi</a>
					</p>
					<p>
						<a class="" href="<?php echo BASE_URL;?>/statisticsystem/statisticquestion">
						<img class="fugue fugue-tables--arrow" alt="" src="<?php echo BASE_URL;?>/img/icons/space.gif"/>Câu hỏi</a>
					</p>
					<p>
						<a class="" href="<?php echo BASE_URL;?>/statisticsystem/statisticclass">
						<img class="fugue fugue-tables--arrow" alt="" src="<?php echo BASE_URL;?>/img/icons/space.gif"/>Lớp học</a>
					</p>
					<p>
						<a class="" href="<?php echo BASE_URL;?>/statisticsystem/statisticuser">
						<img class="fugue fugue-tables--arrow" alt="" src="<?php echo BASE_URL;?>/img/icons/space.gif"/>Người dùng</a>
					</p>
					
				</div>
			</div>
		</div>
	</div>
</div>
