<?php
	header("Content-type: application/vnd.ms-word");
	//header("Content-type: application/vnd.ms-excel");
	header("Content-Disposition: attachment;Filename=Danhsachsinhvien_.doc");
	//header("Content-Disposition: attachment;Filename=Danhsachsinhvien_.xls");
		//header("Content-Disposition: attachment;Filename=Bangdiem_.xls");
	header("Pragma: no-cache");
?>
<div id="globalContainer">
	<div id="content" class="hasLeftCol">
		<div id="contentCol" class="hasRightCol">
			<div id="rightCol" >
				<div class="name-page-cms"><p style="text-align: center;font-weight: 600;font-size: 18px;">TRƯỜNG ĐẠI HỌC CÔNG NGHỆ THÔNG TIN</p><br/>
					<p style="text-align: center;font-weight: 600;font-size: 18px;">KHOA HỆ THỐNG THÔNG TIN </p>
				</div>
			</div>
			<div id="rightCol" >
				<div class="name-page-cms">	Danh sách sinh viên của lớp học: <?php echo $this->class_obj['full_name'];?>
				</div>
			</div>
			<!-- CMS -->
			<?php if (count($this->StudentInClass)>0)  { ?>
				<div>
				<table class="datatable">
					<tr>
						<th>STT</th>
						<th>Mã số sinh viên</th>
						<th>Họ tên</th>
						<th>Khoa</th>
					</tr>
					<?php foreach ($this->StudentInClass as $key=>$StudentInClassItem){ ?>
					<tr>
						<td><?php echo ($key+1); ?></td>
						<td><?php echo $StudentInClassItem['user_obj']['user_code']; ?></td>
						<td><?php echo $StudentInClassItem['user_obj']['firstname']." ".$StudentInClassItem['user_obj']['lastname']; ?></td>
						<td><?php echo $StudentInClassItem['user_obj']['department']; ?></td>
					</tr>
					<?php } ?>
				</table>
				</div>
			<?php } ?>
				
		</div>
	</div>
</div>
