<div id="globalContainer">
	<div id="content" class="hasLeftCol">
		<div id="contentCol" class="hasRightCol">
		<input type="hidden" id="shedule_exam_id" value="<?php echo $this->shedule_exam_id;?>">
		<input type="hidden" id="class_id" value="<?php echo $this->class_obj['id'];?>">
			<div class="back-to-cms-class">
				<a class="button mgt10" href="<?php echo BASE_URL; ?>/classs/" >Quản lý lớp học</a>
			</div>
			<div id="rightCol" >
				<div class="name-page-cms">	Kỳ thi: <?php echo $this->exam_obj['full_name'];?>
				</div>
			
				<div class="name-page-cms">	Điểm làm bài của sinh viên lớp: <?php echo $this->class_obj['full_name'];?>
				</div>
				<div class="back-to-cms-class deleteAlllTestOfClass">
					<a onclick="deleteAlllTestOfClass(); return false;" style="border: 3px solid red;" class="button mgt10" href="#" >Hủy bài làm của cả lớp</a>
					<?php  if($this->flagDisableUpdateLevel=="enable"){
						if($this->auto_update_level != 1){
						?>
						<a id="removeUpdateClassification" onclick="fnUpdateLevelClassification(); return false;" style="border: 3px solid red;" class="button mgt10" href="#" >Cập nhật độ phân cách</a>
					<?php } } ?>
					<a id="DoGradeByHand" onclick="fnDoGradeByHand(); return false;" style="border: 3px solid red;" class="button mgt10" href="#" >Chấm điểm thủ công</a>
					<br/>					
					<br/>
					<br/>
					<a onclick="fnExportExcel(); return false;" class="button mgt10" href="#" >Xuất bảng điểm ra Excel</a>
					<a onclick="fnExportWord(); return false;" class="button mgt10" href="#" >Xuất bảng điểm ra Word</a>
					<a onclick="fnViewLevelOfTest(); return false;" class="button mgt10" href="#" >Xem độ khó-phân cách</a>
					<br/>					
					<br/>
					<br/>
					<a onclick="ReTestAgainAllClass(); return false;" style="border: 3px solid red;" class="button mgt10" href="#" >Cả lớp làm lại bài</a>
					<br/>
					<br/>
					<p class="DoGradeByHand-p-stop-all-test"><label><b> Dừng bài làm của sinh viên cả lớp lại:</b></label>&nbsp;&nbsp;
						<input type="checkbox" name="stop_do_test_now" id="stop_do_test_now" class="stop_do_test_now" onclick="fnStop_do_test_now(this);" >
					</p>
					<br/>
					<p class="DoGradeByHand-p-tip-stop-all-test" style="display: none;">
							<label><b>
								Khi bạn chọn chức năng này thì hệ thống 
								sẽ dừng toàn bộ sinh viên đang làm bài thi.
								Không cho sinh viên tiếp tục làm bài nữa.
							</b></label>
					</p>
				</div>
			</div>
			
			<!-- CMS -->
			<?php if (count($this->StudentInClass)>0)  { ?>
				<div class="table-score-OfTest-student">
				<table class="datatable">
					<tr>
						<th>STT</th>
						<th>Mã số SV</th>
						<th>Họ tên</th>
						<th>Điểm</th>
						<th>Thao tác</th>
					</tr>
					<?php foreach ($this->StudentInClass as $key=>$StudentInClassItem){ ?>
					<tr>
						<td><?php echo ($key+1); ?></td>
						<td><?php echo $StudentInClassItem['user_obj']['user_code']; ?></td>
						<td><?php echo $StudentInClassItem['user_obj']['firstname']." ".$StudentInClassItem['user_obj']['lastname']; ?></td>
                                                <td><?php if(!isset($StudentInClassItem['hist_test_obj']))
							 		 echo "Chưa thi";
							 	  else{ 
							 		echo $StudentInClassItem['hist_test_obj']['total_score']; ?></td>
									<td style="width: 150px;">
										<a class="view-icon" href="#" id="student_tr_<?php echo $StudentInClassItem['hist_test_obj']['id']; ?>" onclick="popupReviewTestStudent(this); return false;"><img class="fugue fugue-eye"  alt="Xem bài làm" title="Xem bài làm" src="<?php echo BASE_URL;?>/img/icons/space.gif"/></a>
										&nbsp;&nbsp;&nbsp;
										<a class="remove-icon" href="#" id="student_tr_<?php echo $StudentInClassItem['hist_test_obj']['id']; ?>" onclick="ajaxStudentReTest(this); return false;"><img class="fugue fugue-cross"  alt="Hủy bài làm" title="Hủy bài làm" src="<?php echo BASE_URL;?>/img/icons/space.gif"/></a>
										&nbsp;&nbsp;&nbsp;
										<?php if($StudentInClassItem['hist_test_obj']['do_test_again']!=1) { ?>
										<a class="remove-icon" href="#" id="student_tr_<?php echo $StudentInClassItem['hist_test_obj']['id']; ?>" onclick="ajaxStudentReDoTestAgain(this); return false;"><img class="fugue fugue-arrow-circle"  alt="Cho làm lại bài" title="Cho làm lại bài" src="<?php echo BASE_URL;?>/img/icons/space.gif"/></a>
										<?php } ?>
									</td>
						<?php } ?>
					</tr>
					<?php } ?>
				</table>
				</div>
			<?php } ?>
			
			<div id="view-container" class="ui-corner-all ui-widget-content">
			</div>
			
			<!-- CMS -->
			<!-- Dialog Add new  -->
			<!-- Dialog Add new  -->		
			<div class="back-to-cms-class">
				<a class="button mgt10" href="<?php echo BASE_URL; ?>/classs/" >Quản lý lớp học</a>
			</div>
				
		</div>
	</div>
</div>

<script language="javascript">
$(document).ready(function(){
	<?php if($this->auto_update_level==1){  ?>
		fnAutoUpdateLevelClassification();
	<?php } ?>
	
  $("p.DoGradeByHand-p-stop-all-test").mouseover(function() {
    	$(".DoGradeByHand-p-tip-stop-all-test").css({'display' : 'inline','width' : '500px'});
  }).mouseout(function(){
    	$(".DoGradeByHand-p-tip-stop-all-test").css({'display' : 'none'});
  });
	
	
});

		function fnExportExcel(){
			var shedule_exam_id = $("#shedule_exam_id").val();
			var class_id = $("#class_id").val();
			if(confirm("Bạn có chắc chắn muốn xuất ra file excel điểm của lớp này không?")==true){
    			 url =  $("#BASE_URL").val()+"/historyofusertest/exportexcelscore/shedule_exam_id/"+shedule_exam_id+"/class_id/"+class_id;
    			 window.location=url;
	    	}
		}
		function fnExportWord(){
			var shedule_exam_id = $("#shedule_exam_id").val();
			var class_id = $("#class_id").val();
			if(confirm("Bạn có chắc chắn muốn xuất ra file word điểm của lớp này không?")==true){
    			 url =  $("#BASE_URL").val()+"/historyofusertest/exportwordscore/shedule_exam_id/"+shedule_exam_id+"/class_id/"+class_id;
    			 window.location=url;
	    	}
		}		
		function fnDoGradeByHand(){
			var shedule_exam_id = $("#shedule_exam_id").val();
			var class_id = $("#class_id").val();
			if(confirm("Bạn có chắc chắn muốn chấm điểm thủ công cho đề thi này?")==true){
    			 url =  $("#BASE_URL").val()+"/historyofusertest/dogradebyhand/shedule_exam_id/"+shedule_exam_id+"/class_id/"+class_id;
   				 newwindow=window.open(url,'PopupDoGradeByhand','scrollbars=yes,resizable=yes,height=540,width=700', 0);
				 if (window.focus) {newwindow.focus()}
    			 //window.location=url;
	    	}
		}
		
		function fnViewLevelOfTest(){
			var shedule_exam_id = $("#shedule_exam_id").val();
			var class_id = $("#class_id").val();
			if(confirm("Bạn có muốn xem độ khó và độ phân cách của đề thi cho lớp này?")==true){
    			 url =  $("#BASE_URL").val()+"/historyofusertest/viewleveltest/shedule_exam_id/"+shedule_exam_id+"/class_id/"+class_id;
   				 newwindow=window.open(url,'PopupViewLevelOfTest','scrollbars=yes,resizable=yes,height=540,width=700', 0);
				 if (window.focus) {newwindow.focus()}
    			 //window.location=url;
	    	}
		}
		
		function fnUpdateLevelClassification(){
			var shedule_exam_id = $("#shedule_exam_id").val();
			var class_id = $("#class_id").val();
			if(confirm("Bạn muốn cập nhật độ khó và độ phân cách cho bài thi này?")==true){
    			 url =  $("#BASE_URL").val()+"/historyofusertest/updatelevelclassification/shedule_exam_id/"+shedule_exam_id+"/class_id/"+class_id;
  				$.ajax({
    					   type: "POST",
    					   url: url+"/token/"+fnGenToken(),
    					   data: "shedule_exam_id="+shedule_exam_id+"&class_id="+class_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
									//$(_this).parent("td").parent("tr").remove();
									alert("Cập nhật độ khó và độ phân cách thành công.");
									$("#removeUpdateClassification").remove();
							}else{
									alert(data['error']);
    						 }
    					   }
    					 }); 

	    	}
		
		}

		function fnAutoUpdateLevelClassification(){
			var shedule_exam_id = $("#shedule_exam_id").val();
			var class_id = $("#class_id").val();
    			 url =  $("#BASE_URL").val()+"/historyofusertest/updatelevelclassification/shedule_exam_id/"+shedule_exam_id+"/class_id/"+class_id;
  				$.ajax({
    					   type: "POST",
    					   url: url+"/token/"+fnGenToken(),
    					   data: "shedule_exam_id="+shedule_exam_id+"&class_id="+class_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
    						 /*
									//$(_this).parent("td").parent("tr").remove();
									alert("Cập nhật độ khó và độ phân cách thành công.");
							*/
									$("#removeUpdateClassification").remove();
							
							}else{
									alert(data['error']);
    						 }
    					   }
    					 }); 

		}

		function deleteAlllTestOfClass(){
			var shedule_exam_id = $("#shedule_exam_id").val();
			var class_id = $("#class_id").val();
			if(confirm("Bạn có chắc chắn muốn xóa tất cả bài thi của lớp học này không?")==true){
  				$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/historyofusertest/deletealltestclass"+"/token/"+fnGenToken(),
    					   data: "shedule_exam_id="+shedule_exam_id+"&class_id="+class_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
									//$(_this).parent("td").parent("tr").remove();
									$(".table-score-OfTest-student").remove();
									html = '<div class="name-page-cms">Xóa toàn bộ bài  thi của lớp học thành công</div>';
									$("#rightCol").html(html);
									
							}else{
									alert("Xóa không thành công, không tồn tại lớp học này.");
    						 }
    					   }
    					 }); 
    	  }
			
		}
		
	function ajaxStudentReTest(_this){
		var histest_id = $(_this).attr("id").replace("student_tr_","")*1;
			if(confirm("Bạn có chắc chắn muốn hủy bài thi của sinh viên này không?")==true){
  				$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/historyofusertest/deletetestonestudent/token/"+fnGenToken(),
    					   data: "hisid="+histest_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
									$(_this).parent("td").parent("tr").remove();
									alert("Xóa thành công bài thi của sinh viên.");
							}else{
									alert("Xóa không thành công, không tồn tại bài thi của sinh viên.");
    						 }
    					   }
    					 }); 
    	}
	}	
		
		
		
	function ajaxStudentReDoTestAgain(_this){
		var histest_id = $(_this).attr("id").replace("student_tr_","")*1;
			if(confirm("Bạn có chắc chắn muốn cho sinh viên này làm lại bài thi không?")==true){
  				$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/historyofusertest/redotestonestudent/token/"+fnGenToken(),
    					   data: "hisid="+histest_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
									$(_this).find(".fugue-arrow-circle").remove();
									alert("Cài đặt cho sinh viên làm lại bài thi thành công.");
							}else{
									alert(data['error']);
    						 }
    					   }
    					 }); 
    	}
	}	
		
		
	function popupReviewTestStudent(_this){
		var histest_id = $(_this).attr("id").replace("student_tr_","")*1;
		var href = $("#BASE_URL").val()+"/historyofusertest/teacherreviewstudenttest/hisid/"+histest_id+"/token/"+fnGenToken();
		newwindow=window.open(href,'name','scrollbars=yes,resizable=yes,height=540,width=700', 0);
		if (window.focus) {newwindow.focus()}
	}
	
	function ReTestAgainAllClass(){
			var shedule_exam_id = $("#shedule_exam_id").val();
			var class_id = $("#class_id").val();
			if(confirm("Bạn có chắc chắn muốn cho cả lớp học này làm lại bài không?")==true){
  				$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/historyofusertest/setupretestagainallclass"+"/token/"+fnGenToken(),
    					   data: "shedule_exam_id="+shedule_exam_id+"&class_id="+class_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
    						 	$(".fugue-arrow-circle").remove();
								alert("Cài đặt cho cả lớp làm lại bài thi thành công.");									
							}else{
									alert("Thao tác không thành công."+data['error']);
    						 }
    					   }
    					 }); 
    	}
	
	}
	
	function fnStop_do_test_now(_this){
		is_check  = $(_this).attr("checked");
		var shedule_exam_id = $("#shedule_exam_id").val();
		var class_id = $("#class_id").val();
		if(is_check){
			if(confirm("Bạn có chắc chắn muốn dừng bài làm cả lớp học này không?")==true){
  				$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/historyofusertest/setupstopalltestinclass"+"/token/"+fnGenToken(),
    					   data: "stop_do_test_now=1&shedule_exam_id="+shedule_exam_id+"&class_id="+class_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
    						 	$(".DoGradeByHand-p-tip-stop-all-test").css({'display' : 'inline','width' : '500px'});
								alert("Cài đặt dừng bài làm cả lớp thành công.");									
							}else{
									alert("Thao tác không thành công."+data['error']);
    						 }
    					   }
    					 }); 
    		}else
    			$(_this).attr("checked",false);
		}else{
			$(".DoGradeByHand-p-tip-stop-all-test").css({'display' : 'none'});
  				$.ajax({
    					   type: "POST",
    					   url: $("#BASE_URL").val()+"/historyofusertest/setupstopalltestinclass"+"/token/"+fnGenToken(),
    					   data: "stop_do_test_now=0&shedule_exam_id="+shedule_exam_id+"&class_id="+class_id,
    					   dataType: "json",
    					   success: function(data){
    						 if(data['success']==true){
    						 	alert("Hủy cài đặt dừng bài làm cả lớp thành công.");
							}else{
									alert("Thao tác không thành công."+data['error']);
    						 }
    					   }
    					 }); 
		
		}
	}
	
			
</script>