<div class="content last ui-widget-content">
	<div class="content-full">
		<div style="width: 98%;padding-left: 5px;">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<div class="cms_table">
				<?php if ($this->Obj['isupdate'] == 0){?>
						<h2>Thêm mới sinh viên vào lớp học</h2>
						<?php }?>
				<?php if ($this->Obj['isupdate'] == 1){?>
						<h2>Chỉnh sửa thông tin sinh viên của 1 lớp học</h2>
						<?php }?>
				<form action="<?php echo BASE_URL; ?>/<?php echo $this->controller;?>/<?php echo $this->action;?>"	method="POST" name="quiz-form" id="">
					<input type="hidden" name="id" value="<?php echo $this->Obj['id'] ;?>">		
					<input type="hidden" name="isupdate" value="<?php echo $this->Obj['isupdate'];?>"/>			
					<table cellpadding="0" cellspacing="0">
						<tr><td class="label">
								Lớp học
							 </td><td class="field_container"><?php echo $this->SltClass("class_id", $this->Obj['class_id']); ?>
						</td></tr>
						<tr><td class="label">
								Tên sinh viên 
								</td><td class="field_container"> 
								<input type="text" name="user_id" style="width: 300px " value="<?php  echo $this->Obj['user_id']; ?>" > <input type="button" value="Import từ file">
						</td></tr>
						<tr><td colspan="5"  style="font-size: 12px; color: white; font-family: tahoma;"  >
								<p align="center">
									<input  type="submit" value="Đồng ý" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">&nbsp;&nbsp;&nbsp;&nbsp;
									<input  type="button" value="Hủy bỏ" onclick="window.location='<?php echo  BASE_URL.'/classhasstudent';  ?>'" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">
								</p>
						</td></tr>
						
					</table>		
				</form>
				<!--  -->
			</div>
		</div>
	</div>
</div>