<?php
	if (count($this->arrError)>0) echo $this->error($this->arrError);
	if(count($this->arrClassId)>0){
	$listClassId = $this->arrClassId;
	$flag_table2 = false;

?>
<br/>
<table class="datatable" >
  <tr>
    <th colspan="8" align="center">Danh sách các lớp mà bạn đang tham gia</th>
  </tr>
   <tr>
    <th>Khóa học</th>
    <th>Tên lớp</th>
    <th>Ngày bắt đầu</th>
    <th>Ngày kết thúc</th>
    <th>Tình trạng</th>
    <th>Thao tác</th>
  </tr>
  
<?php 	foreach ($listClassId as $key=>$listClassIdItem){ 
		$modelsClass = new Default_Models_Classs();
		$modelsClass->find("id",$listClassIdItem );
		if($modelsClass->getId()){
			$modelsCourse = new Default_Models_Course();
			$modelsCourse->find("id",$modelsClass->getCourse_id());
			if($modelsCourse->getId()){
				if($modelsClass->getHidden()=='on'){
?>  
  <tr>
    <td class="name-course-width"><?php echo $modelsCourse->getFull_name(); ?></td>
    <td><?php echo $modelsClass->getFull_name(); ?></td>
    <td><?php echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($modelsClass->getTime_start()) ; ?></td>
    <td><?php echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($modelsClass->getTime_end()); ?></td>
    <td>Mở </td>
    <td style="text-align: center;">
    	<a href="<?php echo BASE_URL; ?>/pagestudent/classstudent/class_id/<?php echo $modelsClass->getId(); ?>" class="ui-state-hover ui-corner-all">Vào lớp </a>
    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    	<!--<a href="<?php // echo BASE_URL; ?>/pagestudent/removestudentclass/class_id/<?php // echo $modelsClass->getId(); ?>" onclick="confirmStudentRemoveClass(this.href); return false;" class="ui-state-hover ui-corner-all">Xóa tên </a>-->
    </td>
    
  </tr>
<?php } else $flag_table2=true;
 } } } ?>
</table>
<br/><br/><br/>
<?php if($flag_table2){?>
<table class="datatable" >
  <tr>
    <th colspan="8" align="center">Danh sách các lớp mà bạn đã tham gia</th>
  </tr>
   <tr>
	<th>Khóa học</th>
    <th>Tên lớp</th>
    <th>Ngày bắt đầu</th>
    <th>Ngày kết thúc</th>
    <th>Tình trạng</th>
    <th>Thao tác</th>
  </tr>
  
<?php 	foreach ($listClassId as $key=>$listClassIdItem){ 
		$modelsClass = new Default_Models_Classs();
		$modelsClass->find("id",$listClassIdItem );
		if($modelsClass->getId()){
			$modelsCourse = new Default_Models_Course();
			$modelsCourse->find("id",$modelsClass->getCourse_id());
			if($modelsCourse->getId()){
				if($modelsClass->getHidden()!='on'){
?>  
  <tr>
    <td class="name-course-width"><?php echo $modelsCourse->getFull_name(); ?></td>
    <td><?php echo $modelsClass->getFull_name(); ?></td>
    <td><?php echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($modelsClass->getTime_start()) ; ?></td>
    <td><?php echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($modelsClass->getTime_end()); ?></td>
    <td>Đóng</td>
    <td>
    	<a href="<?php echo BASE_URL; ?>/pagestudent/classstudent/class_id/<?php echo $modelsClass->getId(); ?>" class="ui-state-hover ui-corner-all">Vào lớp học </a>
    </td>
  </tr>
<?php } } } } ?>
</table>
<?php  } ?>
<!--  -->
<a class="button mgt10" href="<?php echo BASE_URL; ?>/pagestudent/registerclassincourse/courseid/<?php echo $this->CourseObj['id']; ?>" >Tham gia lớp học khác của khóa học này</a>

<?php
}elseif(count($this->CourseObj)>0){
	
 	 echo '<h2 style="text-align: center;">Hiện tại bạn chưa tham gia lớp học nào của khóa học:<br/><font style="color: #1484e6; font-weight: bold;" >"'.$this->CourseObj['full_name'].'"</font><br/>';
	 echo  '<br/> Tham gia <a href="'.BASE_URL.'/pagestudent/registerclassincourse/courseid/'.$this->CourseObj['id'].'" > đăng ký lớp học</a></h2>';
}else{
 	 echo '<h2 style="text-align: center;">Hiện tại bạn chưa tham gia khóa học nào.<br/>';
	 echo  '<br/> Tham gia <a href="'.BASE_URL.'/pagestudent/registerclass/" > đăng ký khóa học</a></h2>';
}
?>
<script type="text/javascript">
<!--
  function confirmStudentRemoveClass(href){
  	if(confirm("Bạn có chắc chắn muốn rút tên khỏi lớp học đã chọn không?")==true){
  		window.location =href;
  	}
  }		
//-->
</script>

