<form action="<?php echo BASE_URL; ?>/pagestudent/studentmanagecourse"	method="POST" >
<div class="wrapperStudentManageCourse">
<?php if($this->success=="success"){ ?> 
<div class="messageSaveSuccess">
	<ul style="list-style: none;"><li>
		<label style="color: #00AEEF; font-size: 15px; font-weight: 1110;"> Lưu lại thành công </label> 
	</li></ul>
</div>
<?php } ?>
<?php
	if (count($this->arrError)>0) echo $this->error($this->arrError);
	if(count($this->arr_course)>0){
?>
<br/>
<br/>
<a class="button mgt10" href="<?php echo BASE_URL; ?>/pagestudent/registerclass/"><span>Tham gia khóa học khác</span></a>
<br/>
<br/>
<br/>
<table class="datatable tableStudentCourse" >
  <tr>
    <th colspan="8" align="center">Danh sách khóa học mà bạn đang tham gia</th>
  </tr>
   <tr>
    <th>Khóa học</th>
    <!--<th>Ngày bắt đầu</th>-->
    <!--<th>Ngày kết thúc</th>-->
    <th>Tình trạng</th>
    <th>Chọn làm mặc định cho lần đăng nhập sau</th>
  </tr>
  
<?php
foreach ($this->arr_course as $key=>$arr_courseItem){ 
?>  
  <tr>
    <td class="name-course-width"><?php echo $arr_courseItem['full_name']; ?></td>
    <!--<td><?php /* echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($arr_courseItem['time_start']) ; ?></td>-->
    <!--<td><?php echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($arr_courseItem['time_end']); */ ?></td>-->
    <td><?php if($arr_courseItem['hidden']=='on') echo "Mở"; else echo 'Đóng'; ?> </td>
    <?php $check=""; if($key==0) $check="checked='checked'"; ?>
    <td style="text-align: center;"><input type="radio" <?php echo $check; ?> name="rdCourseDefault" value="<?php echo $arr_courseItem['id']; ?>"> </td>
  </tr>
<?php } ?>
</table>
<br/><br/><br/>
<div class="StudentManageCourse-submit">
	<input type="submit" value="Lưu lại">
</div>
<?php
}else{
	
 	 echo '<h2 style="text-align: center;">Hiện tại bạn chưa tham gia khóa học nào cả.<br/>';
	 echo  '<br/> Tham gia <a href="'.BASE_URL.'/pagestudent/registerclass/" > đăng ký khóa học</a></h2>';
}
?>
</div>
</form>