<div class="content last ui-widget-content">
	<div class="content-full">
		<div style="width: 98%;padding-left: 5px;">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<div id="">
				<?php if ($this->Obj['isupdate'] == 1){?>
						<label style="font-size: 15pt; color: silver;">Chỉnh sửa thông tin lớp học</label>
						<?php }?>
				<form action="<?php echo BASE_URL; ?>/<?php echo $this->controller;?>/<?php echo $this->action;?>"	method="POST" name="quiz-form" id="">
					<input type="hidden" name="id" value="<?php echo $this->Obj['id'] ;?>">		
					<input type="hidden" name="isupdate" value="<?php echo $this->Obj['isupdate'];?>"/>			
					<table>
						<tr><td>
								<label>Được xem đáp án</label> 
								</td><td> <input type="checkbox" name="view_corect" <?php if($this->Obj['view_corect']=='on') echo "view_corect"; ?> >
						</td></tr>
						<tr><td >
								<label>Được xem phản hồi </label> 
								</td><td> <input type="checkbox" name="view_feedback" <?php if($this->Obj['view_feedback']=='on') echo "view_feedback"; ?> >
						</td></tr>
						<tr><td colspan="5"  style="font-size: 12px; color: white; font-family: tahoma;"  >
								<p align="center">
									<input  type="submit" value="Đồng ý" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">&nbsp;&nbsp;&nbsp;&nbsp;
									<input  type="button" value="Hủy bỏ" onclick="window.location='<?php echo  BASE_URL.'/historyofusertest';  ?>'" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">
								</p>
						</td></tr>
						
					</table>		
				</form>
				<!--  -->
			</div>
		</div>
	</div>
</div>