<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Login Page</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="<?php echo BASE_URL;?>/media/css/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?php echo BASE_URL;?>/media/css/blueprint/print.css" type="text/css" media="print">
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="<?php echo BASE_URL;?>/media/css/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    <link rel="stylesheet" href="<?php echo BASE_URL;?>/media/css/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?php echo BASE_URL;?>/media/css/blueprint/plugins/buttons/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?php echo BASE_URL;?>/media/css/blueprint/plugins/sprites/screen.css" type="text/css" media="screen, projection">
  </head>
  <body>
  	<div class="teacher_banner">
		<p class="student-banner-right" style="text-align: center;">
			<?php echo $this->render("header.phtml");?>	
		</p>	
	</div>	
	<div style="padding-top: 20px;">

<?php
/* Get full name link request
if ($_SERVER['SERVER_PORT']!=443) {
$sslport=443; //whatever your ssl port is
$url = "https://". $_SERVER['SERVER_NAME'] . ":" . $sslport . $_SERVER['REQUEST_URI'];
echo BASE_URL;
echo $url; die(); 
header("Location: $url");
}
*/
?>	
	
  	  <div class="loginbox">	
	      <div class="" style="margin: 0pt auto;">
			          <?php if($this->errMsg){?>              
			              <div class="ui-state-error" style="padding: 3px;">
			              	<?php echo $this->errMsg;?>
			              </div>
					  <?php }?>
	                  <form action="<?php echo BASE_URL;?>/auth/login" method="POST">
	                  	  <table class='ui-corner-bottom' style="float: left;">
	                  	  	<caption class='ui-state-default ui-corner-top'>
								Đăng nhập hệ thống
							</caption>
							<tr>
								<td><img src="<?php echo BASE_URL; ?>/img/user.png" alt="User Icon" />
								</td>
								<td>
									<table>
				                  	  	<tr>
				                  	  		<td><label>Tài khoản:</label></td>
				                  	  		<td><input type="text" name="txtUserName" class="input-login" value="" /></td>
				                  	  	</tr>
				                  	  	<tr>
				                  	  		<td><label>Mật khẩu:</label></td>
				                  	  		<td><input type="password" name="txtPassword" class="input-login" value="" /></td>
				                  	  	</tr>
									</table>
								</td>
								</tr>
		                  	  	<tr>
		                  	  		<td colspan="3" style="text-align: center;">
		                  	  			<p>
					                          <button type="submit" class="btLogin positive">
					                          <img src="<?php echo BASE_URL;?>/img/icons/space.gif" 	class='fugue-arrow-curve-000-double'>
					                            	Đăng nhập
					                          </button>
					                          <button type="button" class="btLogin negative" onclick="window.location='<?php echo  BASE_URL.'/register';  ?>'">
					                          		<img src="<?php echo BASE_URL;?>/img/icons/space.gif" class='fugue-key--arrow'>
					                            	Đăng ký
					                          </button>
					                	<p>        
		                  	  		</td>
		                  	  	</tr>
							<tr>
<!--								<td colspan="2" style="font-weight: 600;">
									Để dùng thử sản phẩm: hãy đăng nhập hệ thống dưới các tài khoản sau
									<ul style="text-align: left;">
										<li><b>1. Học viên</b>  - Tài khoản: hocvien  - Mật khẩu 123456</li>
										<li><b>2. Giảng viên</b> - Tài khoản: giangvien  - Mật khẩu 123456</li>
									</ul>
								</td>-->
							</tr>
		                  	  	
	                  	  </table>
	                  </form>
	     </div>
	  </div>	
	  <div class="browser-need">
	  	<p>
	  	Hệ thống chạy tốt trên Firefox, Google Chrome, Opera, Internet Explorer 8
	  	</p> 
	  </div>
	  
	</div>        
  </body>
</html>


