<?php echo $this->doctype(); ?>
<html>
<head>
	<?php  echo  $this->headMeta(); ?>
	<?php  echo  $this->headTitle(); ?>
	<?php  //echo  $this->headLink(); ?>
	<?php  //echo  $this->jQuery(); ?>
	<link type="text/css" rel="stylesheet" href="<?php echo BASE_URL;?>/css/student.css">
	<title>Permisson Denied</title>	
</head>
<body>

<input type="hidden" name="BASE_URL" id="BASE_URL" value="<?php echo BASE_URL;?>">
<div class="student_main_content">
	<div class="student_head headerWrapper">
		<div class="student_banner headerWrapper">
			<p class="student-banner-right">
				<?php echo $this->render("header.phtml");?>	
			</p>	
		</div>	
		<div class="student_head_nav">
			<ul>
				<?php 
					$auth = Zend_Auth::getInstance();
					if ($auth->hasIdentity()){
			  			$userhaslogin = $auth->getStorage()->read();  	
				?>				
				<li>
					<a class="linkNav" href="<?php echo BASE_URL;?>/auth/logout" class="">Đăng xuất</a>
				</li>		
				<?php }else { ?>
				<li>
					<a class="linkNav" href="<?php echo BASE_URL;?>/auth/login" class="">Đăng nhập</a>
				</li>		
				<?php } ?>
			</ul>
		</div>	
	</div>
	<div class="student_wrapper">
		<span class="message-page-notfound">
			<h2 style="color: #00ADEF;">Bạn không được quyền vào trang này. Trở lại <a href="<?php echo BASE_URL;?>" >trang chủ </a> </h2>
		</span>
	</div>
	<div style="padding-top: 400px;" >
	<?php echo $this->render("footer.phtml");?>
	</div>
</div>
</body>
</html>