<div class="content last ui-widget-content">
	<div class="content-full">
		<div style="width: 98%;padding-left: 5px;">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<div class="cms_table">
				<?php if ($this->Obj['isupdate'] == 0){?>
						<h2>Thêm mới lớp học</h2>
						<?php }?>
				<?php if ($this->Obj['isupdate'] == 1){?>
						<h2>Chỉnh sửa thông tin lớp học</h2>
						<?php }?>
				<form action="<?php echo BASE_URL; ?>/<?php echo $this->controller;?>/<?php echo $this->action;?>"	method="POST" name="quiz-form" id="">
					<input type="hidden" name="id" value="<?php echo $this->Obj['id'] ;?>">		
					<input type="hidden" name="isupdate" value="<?php echo $this->Obj['isupdate'];?>"/>			
					<table cellpadding="0" cellspacing="0">
						<tr><td class="label">
								Tên lớp học:
								</td><td class="field_container"> <input type="text"  name="full_name" style="width: 300px "   value="<?php  echo $this->Obj['full_name']; ?>" >
						</td></tr>
						<tr><td class="label">
								Tên viết tắt: 
								</td><td class="field_container"> <input type="text" name="short_name"  style="width: 200px "   value="<?php  echo $this->Obj['short_name']; ?>" >
						</td></tr>
						<tr><td class="label">
								Môn học của lớp: 
								</td><td class="field_container"> <?php echo $this->SltSubject("subject_id", $this->Obj['subject_id']); ?>
						</td></tr>
						<tr><td class="label">
								Khóa học: 
								</td><td class="field_container"> <?php echo $this->SltCourse("course_id", $this->Obj['course_id']); ?>
						</td></tr>
						<tr><td class="label">
								</td><td class="field_container">
								<span class="date-time-of-course">
								</span>
						</td></tr>
						
						<tr><td class="label">
								 Thời gian bắt đầu lớp học: 
								</td><td class="field_container"> <input type="text" id="datepicker1" name="time_start"  style="width: 200px "   value="<?php  echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($this->Obj['time_start']); ?>" >
						</td></tr>
						<tr><td class="label">
								 Thời gian kết thúc lớp học: 
								</td><td class="field_container"> <input type="text" id="datepicker2" name="time_end"  style="width: 200px "   value="<?php  echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($this->Obj['time_end']); ?>" >
						</td></tr>
						<tr><td class="label">
								 Thời gian bắt đầu đăng ký học: 
								</td><td class="field_container"> <input type="text" id="datepicker3" name="time_start_register"  style="width: 200px "   value="<?php  echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($this->Obj['time_start_register']); ?>" >
						</td></tr>
						<tr><td class="label">
								 Thời gian kết thúc đăng ký học: 
								</td><td class="field_container"> <input type="text" id="datepicker4" name="time_end_register"  style="width: 200px "   value="<?php  echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($this->Obj['time_end_register']); ?>" >
						</td></tr>
						<tr><td class="label">
								Số sinh viên tối đa cho lớp:
								</td><td class="field_container"> <input type="text" name="max_user"  onchange="validateNum(this);return false;" style="width: 200px "   value="<?php  echo $this->Obj['max_user']; ?>" >
						</td></tr>
						<tr><td class="label">
								Hiện lớp học:
								</td><td class="field_container">  <input type="checkbox" name="hidden" <?php if($this->Obj['hidden']=='on') echo "checked='checked'"; ?> >
								(Nếu tick vào thì lớp học sẽ được hiện trên danh sách cho sinh viên đăng ký, nếu không tick thì coi như lớp học bị khóa, sinh viên không thể đăng ký lớp học này)
						</td></tr>
						
						<tr><td colspan="3">
							<p>
								<label>Ghi chú:</label>
								<textarea class="class-note-short-editor" name="note" rows="3" cols="20"><?php  echo $this->Obj['note']; ?></textarea>
							</p>
						</td></tr>
						<tr><td colspan="5"  style="font-size: 12px; color: white; font-family: tahoma;"  >
								<p align="center">
									<input  type="submit" value="Đồng ý" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">&nbsp;&nbsp;&nbsp;&nbsp;
									<input  type="button" value="Hủy bỏ" onclick="window.location='<?php echo  BASE_URL.'/classs';  ?>'" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">
								</p>
						</td></tr>
						
					</table>		
				</form>
				<!--  -->
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
			$(document).ready(function(){
				initEditorByClassShotcut("class-note-short-editor",300,false,true);
				
				$("#course_id").change(function(){
					$.ajax({
			    				type: "POST",
			    				url: $("#BASE_URL").val()+"/exam/getinfocourseobj"+"/token/"+fnGenToken(),
			    				data: "course_id="+$("#course_id").val(),
			    				dataType: "json",
			    				success: function(data){
				    				if(data['success']==true){
				    					if(data['course_obj']==1)
				    						$(".date-time-of-course").html("");
				    					else{
											var html = '';	
											html += '<p style="color: #00AEEF;font-weight: bold;"> Thời gian bắt đầu khóa học:   '+data['course_obj']['time_start']+'</p>';  
											html += '<p style="color: #00AEEF;font-weight: bold;"> Thời gian kết thúc khóa học:  '+data['course_obj']['time_end']+' </p>';
											html += '<p style="color: #FA9300;font-weight: bold;"> Thời gian học của lớp học phải nằm trong thời gian mở khóa học </p>';
											$(".date-time-of-course").html(html);
										}
				    				}else
				    					alert("Có lỗi "+data['error']); 
			    				}
							});					
					
				});
				
			});
</script>	