<form action="<?php echo BASE_URL; ?>/pagestudent/editinfo/user_id/<?php echo $this->Obj['id'] ;?>"	method="POST" >
<input type="hidden" name="id" value="<?php echo $this->Obj['id'] ;?>">		

<div class="big-div-info-user-edit">
<div>
                <br/>
                <h3 style="color: #1484e6; font-weight: bold; padding-left: 20px;" >Thông tin tài khoản</h3>
            </div>
<div id="tabs">
	<ul style="height: 30px;">
		<li><a href="#tabs-1">Thông tin tài khoản</a></li>
		<li><a href="#tabs-2">Chỉnh sửa thông tin tài khoản</a></li>
	</ul>
	<div id="tabs-1">
					<table>
						<tr><td class="info-student-detail">
								<label>Tên đăng nhập: </label> 
								</td><td class="info-student-detail-right"> 
								<label><?php  echo $this->Obj['username']; ?></label>
						</td></tr>
						<tr><td class="info-student-detail">
								<label>Mã số: </label> 
								</td><td class="info-student-detail-right">
								<label><?php  echo $this->Obj['user_code']; ?></label>
						</td></tr>
						<tr><td class="info-student-detail">
								<label>Họ Tên: </label> 
								</td><td class="info-student-detail-right">
								<label><?php  echo $this->Obj['firstname']." ".$this->Obj['lastname'];  ?></label>
						</td></tr>
							<tr><td class="info-student-detail">
									<label>Khoa : </label> 
									</td><td class="info-student-detail-right">
									<label><?php  echo $this->Obj['department']; ?></label>
							</td></tr>
						 
							<tr><td class="info-student-detail">
									<label>Email: </label> 
									</td><td class="info-student-detail-right">
									<label><?php  echo $this->Obj['email']; ?></label>
							</td></tr>
							<tr><td class="info-student-detail">
									<label>Yahoo: </label> 
									</td><td class="info-student-detail-right">
									<label><?php  echo $this->Obj['yahoo']; ?></label>
							</td></tr>
							<tr><td class="info-student-detail">
									<label>Skyper: </label> 
									</td><td class="info-student-detail-right">
									<label><?php  echo $this->Obj['skyper']; ?></label>
							</td></tr>
							<tr><td class="info-student-detail">
									<label>Phone: </label> 
									</td><td class="info-student-detail-right"><label><?php  echo $this->Obj['phone']; ?></label>
							</td></tr>
							<tr><td class="info-student-detail">
									<label>Địa chỉ: </label> 
									</td><td class="info-student-detail-right">
									<label><?php  echo $this->Obj['address']; ?></label>
							</td></tr>
							<tr><td class="info-student-detail">
									<label>Thành phố: </label> 
									</td><td class="info-student-detail-right">
									<label><?php  echo $this->Obj['city']; ?></label>
							</td></tr>
						
						<tr><td colspan="5"  style="font-size: 12px; color: white; font-family: tahoma;"  >
							<p align="center">
								<input  type="button" value="Đổi mật khẩu" onclick="window.location='<?php echo  BASE_URL.'/auth/changepw';  ?>'"  style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">&nbsp;&nbsp;&nbsp;&nbsp;
								<!--  <input  type="button" value="Xóa tên tôi khỏi khóa học hiện tại" onclick="window.location='<?php // echo  BASE_URL.'/';  ?>'" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">  -->
							</p>
						</td></tr>
						
					</table>		

	</div>
	<div id="tabs-2" style="width: 500px">
	<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
	<?php if ($this->msgSuccess == 'success') echo $this->Success(); ?>
			<table>
						<tr><td class="edit-info-student-detail" >
								<label>Họ và tên đệm:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="firstname"  style="width: 200px;font-size: 15px; "   value="<?php  echo $this->Obj['firstname']; ?>" >
						</td></tr>
						<tr><td class="edit-info-student-detail" >
								<label>Tên:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="lastname"  style="width: 200px;font-size: 15px;  "   value="<?php  echo $this->Obj['lastname']; ?>" >
						</td></tr>
						<tr><td class="edit-info-student-detail" >
								<label>Học khoa:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="department"  style="width: 200px ;font-size: 15px; "   value="<?php  echo $this->Obj['department']; ?>" >
						</td></tr>
						<tr><td class="edit-info-student-detail" >
								<label>Email:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="email"  style="width: 200px;font-size: 15px;  "   value="<?php  echo $this->Obj['email']; ?>" >
						</td></tr>
						<tr><td class="edit-info-student-detail" >
								<label>Yahoo:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="yahoo"  style="width: 200px;font-size: 15px;  "   value="<?php  echo $this->Obj['yahoo']; ?>" >
						</td></tr>
						<tr><td class="edit-info-student-detail" >
								<label>Skyper:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="skyper"  style="width: 200px;font-size: 15px;  "   value="<?php  echo $this->Obj['skyper']; ?>" >
						</td></tr>
						<tr><td class="edit-info-student-detail" >
								<label>Phone:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="phone"  style="width: 200px ;font-size: 15px; "   value="<?php  echo $this->Obj['phone']; ?>" >
						</td></tr>
						<tr><td class="edit-info-student-detail" >
								<label>Địa chỉ:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="address"  style="width: 200px ;font-size: 15px; "   value="<?php  echo $this->Obj['address']; ?>" >
						</td></tr>
						<tr><td class="edit-info-student-detail" >
								<label>Thành phố:</label> 
								</td><td class="edit-info-student-detail-right">
								<input type="text" name="city"  style="width: 200px ;font-size: 15px; "   value="<?php  echo $this->Obj['city']; ?>" >
						</td></tr>
						<tr><td colspan="5"  style="font-size: 12px; color: white; font-family: tahoma;"  >
							<p align="center">
								<input  type="submit" value="Lưu lại" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">&nbsp;&nbsp;&nbsp;&nbsp;
							</p>
						</td></tr>
						
			</table>
		
	</div>
</div>

</div><!-- End info-student -->

</form>


<script type="text/javascript" language="javascript">	
	$(document).ready(function(){
		$( "#tabs" ).tabs();
		<?php if($this->selectedTab =="editInfo") 	 echo '$("#tabs").tabs("select", 1);'; ?>
	});
	/*
	$(function() {
		$( "#tabs" ).tabs();
	}); 
	*/
</script>