
<form id="form" name="form" method="post" action="<?php echo BASE_URL ?>/">
<?php 
		$auth = Zend_Auth::getInstance();
		if ($auth->hasIdentity()){
  		$userhaslogin = $auth->getStorage()->read();  
		$modelsUser = new Default_Models_User();
		$modelsUser->find("id",$userhaslogin->id);
		$arrInfoUser = $modelsUser->toArray();
  		
	?>
			<div class="">
				<fieldset>
				<legend> Thông tin tài khoản</legend>

						<table class="table-td-user-info">
							<tr>
								<td>Họ Tên: </td>
								<td><?php echo $arrInfoUser['firstname']." ".$arrInfoUser['lastname'];?></td>
							</tr>
							<tr>
								<td>Thuộc nhóm: </td>
								<td><?php 
									$models_group = new Default_Models_GroupUser();
									$models_group->find("id",$userhaslogin->group_id);
									if($models_group->getId())
										echo $models_group->getGroup_name();  
									?></td>
							</tr>
							<tr>
								<td align="center" colspan="2">
									<a href="<?php echo BASE_URL;?>/auth/changepw" class="changepass">Đổi mật khẩu</a>
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<a href="<?php echo BASE_URL;?>/pagestudent/editinfo/user_id/<?php echo $userhaslogin->id ?>" class="">Tài khoản</a>
								</td>
							</tr>
						</table>

				</fieldset>
			</div>              

	<?php } ?>
</form>
		<p align="center">
			<img src="<?php echo BASE_URL;?>/media/images/backgrounds/logo_is.jpg" width="200" height="200">
		</p>	
