<div class="content last ui-widget-content">
	<div class="content-full">
		<div style="width: 98%;padding-left: 5px;">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<div class="cms_table">
				<div class="tintuc">
					<div class="bgtin"><span><p class="news-category-name"> Chuyên mục:&nbsp; <?php echo $this->category['name'];?></p></span></div>				
				</div>
				<div class="tintuc">
					<div class="bgtin"><span><p class="news-title"><?php echo $this->news['title'];?></p></span></div>				
				</div>
				 <div align="right">
					 <font style="font-size: 13; color: silver; font-weight: bold ">Ngày:&nbsp; <?php echo Zend_View_Helper_FormatDate::convertSecondToDateTimeHasHour($this->news['created']);?></font>
				</div>
				
				<?php echo $this->news['content'];?>
				 <div align="right">
					 <font style="font-size: 13; color: silver; font-weight: bold "><p class="news-title" style="font-size: 13px"> Người đăng:&nbsp;  <?php echo $this->user_create;?></p></font>
				</div>
				
				<?php echo $this->otherNews($this->category['id']);?>			
			</div>
		</div>
	</div>
</div>
