<?php  echo $this->sidebarAdmin('Study Online', 'question'); ?>
<div class="content last ui-widget-content">
	<div class="content-full">
		<!-- viewQuestion($question_id,$answer_of_user = array(),$review_test=0,$view_corect=0,$view_feedback=0,$view_send_result=0,$view_score=0) -->
		<form action="" method="post"> 
		
		<?php
			$question_id    = $this->data['question_id'];
			$question_score = $this->data['question_score'];  
			$answer_of_user = $this->data['question'];
			if(count($question_id)>0){
				foreach ($question_id as $key=>$question_idItem){
					echo  $this->viewQuestion($question_idItem,$answer_of_user[$question_idItem],$this->review_test,$this->view_corect,$this->view_feedback,$this->view_send_result,$question_score[$key]);
					echo "<hr/>";
				}
			} 
		 ?>		
		 <input type="submit">
		</form>
		<hr/>
	</div>
</div>