<a href="<?php echo BASE_URL;?>/" style="margin-left: 5px; text-decoration: none;"><b>Trở về trang chủ</b></a>
<h3 style="text-align:center;color: #00AEEF; font-weight:600;  padding-left:5px; padding-top: 10px;padding-bottom:5px; border-top: solid 1px black;">THAY ĐỔI MẬT KHẨU</h3>
<div class="cms_table">
<?php if(!empty($this->errMsg)) {?>
<div class="ui-widget" id="errorMsg">
	<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
		<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
		<strong>Thông báo lỗi:</strong> <?php echo $this->errMsg;?> </p>
	</div>
</div>
<?php } ?>
<form method="post" action="<?php echo BASE_URL ?>/auth/changepw">
<table width="494" height="148" border="0">
  <tr>
    <td width="167" height="30" class="label" >Mật khẩu hiện tại</td>
    <td width="262" class="field_container"><input type="password" name="txtCurrentPass" id="txtCurrentPass" maxlength="64"/> <font color="red">*</font></td>
  </tr>
  <tr>
    <td height="35" class="label">Mật khẩu mới</td>
    <td class="field_container"><input type="password" name="txtNewPass" id="txtNewPass" maxlength="64"/> <font color="red">*</font></td>
  </tr>
  <tr>
    <td height="38" class="label">Xác nhận mật khẩu</td>
    <td class="field_container"><input type="password" name="txtConfirmPass" id="txtConfirmPass" maxlength="64"/> <font color="red">*</font></td>
  </tr>
  <tr>
    <td height="35">&nbsp;</td>
    <td><input class="Control_Button0" type="submit" name="button" id="button" value="   Lưu thay đổi  " /> &nbsp;&nbsp;
      <input class="Control_Button0" type="button" name="button2" id="button2" value="  Hủy bỏ " onclick="window.location='<?php echo  BASE_URL . '/index';  ?>'"/></td>
  </tr>
</table>
</form>
</div>

