<div class="content last ui-widget-content">
	<div class="content-full">
		<div style="width: 98%;padding-left: 5px;">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<div class="cms_table">
				<?php if ($this->Obj['isupdate'] == 0){?>
						<h2>Thêm mới khóa học</h2>
						<?php }?>
				<?php if ($this->Obj['isupdate'] == 1){?>
						<h2>Chỉnh sửa thông tin khóa học</h2>
						<?php }?>
				<form action="<?php echo BASE_URL; ?>/<?php echo $this->controller;?>/<?php echo $this->action;?>"	method="POST" name="quiz-form" id="">
					<input type="hidden" name="id" value="<?php echo $this->Obj['id'] ;?>">		
					<input type="hidden" name="isupdate" value="<?php echo $this->Obj['isupdate'];?>"/>			
					<table cellpadding="0" cellspacing="0">
						<tr><td class="label">
								Tên khóa học: 
								</td><td class="field_container">
								<textarea style="font-size:16px; font-weight:bold;" name="full_name" rows="3" cols="20"><?php  echo $this->Obj['full_name']; ?></textarea>
						</td></tr>
						<tr><td class="label">
								Tên viết tắt:
								</td><td class="field_container"><input type="text" name="short_name"  style="width: 200px "   value="<?php  echo $this->Obj['short_name']; ?>" >
						</td></tr>
						<tr><td class="label">
								 Thời gian bắt đầu khóa học: 
								</td><td class="field_container"><input type="text" id="datepicker1" name="time_start"  style="width: 200px "   value="<?php  echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($this->Obj['time_start']);?>" >
						</td></tr>
						<tr><td class="label">
								 Thời gian kết thúc khóa học:
								</td><td class="field_container"><input type="text" id="datepicker2" name="time_end"  style="width: 200px "   value="<?php  echo Zend_View_Helper_FormatDate::convertYmdToMdyJustDate($this->Obj['time_end']); ?>" >
						</td></tr>
						<tr><td class="label">
								Mở khóa học: 
								</td><td class="field_container"> <input type="checkbox" name="hidden"  <?php if($this->Obj['hidden']=='on') echo "checked='checked'"; ?> >
						</td></tr>
						<tr><td colspan="2">
								<p>
									<label>Ghi chú:</label>
									<textarea class="course-short-editor" name="summary" rows="3" cols="20"><?php  echo $this->Obj['summary']; ?></textarea>
								</p>
						</td></tr>
						<tr><td colspan="5"  style="font-size: 12px; color: white; font-family: tahoma;"  >
							<p align="center">
								<input  type="submit" value="Đồng ý" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">&nbsp;&nbsp;&nbsp;&nbsp;
								<input  type="button" value="Hủy bỏ" onclick="window.location='<?php echo  BASE_URL.'/course';  ?>'" style="font-size: 15px;" class="add-answer-icon ui-state-default ui-corner-all">
							</p>
						</td></tr>
						
					</table>		
				</form>
				<!--  -->
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
			$(document).ready(function(){
				initEditorByClassShotcut("course-short-editor",500,false,true);
			});
</script>	