<div id="blueBar"></div>
<div id="globalContainer">
	<?php echo $this->render("navigation.phtml");?>
	<div id="content" class="hasLeftCol">
		<div id="contentCol" class="hasRightCol">
			<div id="rightCol" >
				<div class="name-page-cms">	Quản lý lịch thi
				</div>
			</div>
			<div id="contentArea">
			
			<!-- CMS -->
			<input type="hidden" id="CMS_SERVERSIDE" value="<?php echo BASE_URL;?>/sheduleexam/serverside">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<?php
				/* Giải thích đoạn: array("subject_id"=>$this->SltSubject("inline-search-3"))
				 * cái selection ở inline search ứng với cột subject_id -> trên table sau khi view ra nó ở cột 3 tính từ 0
				 * từ inline-search là bắt buộc 
				 */
				echo $this->table("table_sheduleexam",$this->cols_view_title,"sheduleexam", $this->cols_view,
					array(
						"class_id"=>$this->SltClass("inline-search-3",null)
						));				
			?>
			
			<?php //echo $this->table("table_sheduleexam",$this->cols_view_title,"sheduleexam");  ?>
			<script language="javascript">
				$(document).ready(function(){
					InitJqueryDataTable("#table_sheduleexam","");
					$(".search-on-table").find("input[type='text']:eq(2)").hide();
					$("#inline-search-3").change(function(){
						oTable.fnFilter( this.value,$(this).attr("name").replace("inline-search-","")*1); 
					});
					
				});				
			</script>
			
			<div id="view-container" class="ui-corner-all ui-widget-content">
			</div>
			
			<!-- CMS -->
			<!-- Dialog Add new  -->
			<!-- Dialog Add new  -->			
			</div>
		</div>
	</div>
</div>
