<?php
// application/layouts/scripts/layout.phtml
?>
<?php echo $this->doctype(); ?>
<html>
<head>
	<?php  echo  $this->headMeta(); ?>
	<?php  echo  $this->headTitle(); ?>
	<?php  echo  $this->headLink(); ?>
	<?php  echo  $this->jQuery(); ?>	
</head>
<body>
<div class="main_content">
	<input type="hidden" name="BASE_URL" id="BASE_URL" value="<?php echo BASE_URL;?>">
	<?php  echo  $this->layout()->content ?>
</div>
</body>
</html>
