<div id="blueBar"></div>
<div id="globalContainer">
	<?php echo $this->render("navigation.phtml");?>
	<div id="content" class="hasLeftCol">
		<div id="leftCol">			
		</div>
		<div id="contentCol" class="hasRightCol">
			<div id="rightCol" >
			</div>
			<div id="contentArea">
			<!-- CMS -->
			<input type="hidden" id="CMS_SERVERSIDE" value="<?php echo BASE_URL;?>/permissionusercustom/serverside">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<?php echo $this->table("table_permissionusercustom",$this->cols_view_title,"permissionusercustom");?>
			<script language="javascript">
				$(document).ready(function(){
					InitJqueryDataTable("#table_permissionusercustom","");
				});				
			</script>
			
			<div id="view-container" class="ui-corner-all ui-widget-content">
			</div>
			
			<!-- CMS -->
			<!-- Dialog Add new  -->
			<!-- Dialog Add new  -->			
			</div>
		</div>
	</div>
</div>