<div id="blueBar"></div>
<div id="globalContainer">
	<div id="content" class="hasLeftCol">
		<div id="contentCol" class="hasRightCol">
			<div id="rightCol" >
				<div class="name-page-cms">	Quản lý nhóm người dùng
				</div>
			</div>
			<div id="contentArea">
			<!-- CMS -->
			<input type="hidden" id="CMS_SERVERSIDE" value="<?php echo BASE_URL;?>/groupuser/serverside">
			<?php if (count($this->arrError)>0) echo $this->error($this->arrError); ?>
			<?php echo $this->table("table_groupuser",$this->cols_view_title,"groupuser");?>
			<script language="javascript">
				$(document).ready(function(){
					InitJqueryDataTable("#table_groupuser","");
				});				
			</script>
			
			<div id="view-container" class="ui-corner-all ui-widget-content">
			</div>
			
			<!-- CMS -->
			</div>
		</div>
	</div>
</div>