<?php
	header("Content-type: application/vnd.ms-word");
	//header("Content-type: application/vnd.ms-excel");
	header("Content-Disposition: attachment;Filename=ThongKeNguoiDung_.doc");
	//header("Content-Disposition: attachment;Filename=Danhsachsinhvien_.xls");
		//header("Content-Disposition: attachment;Filename=Bangdiem_.xls");
	header("Pragma: no-cache");
?>
<div id="blueBar"></div>
<div id="globalContainer">
	<?php echo $this->render("navigation.phtml");?>
	<div id="content" class="hasLeftCol">
			<div id="rightCol" >
				<div class="name-page-cms"><p style="text-align: center;font-weight: 600;font-size: 18px;">TRƯỜNG ĐẠI HỌC CÔNG NGHỆ THÔNG TIN</p><br/>
					<p style="text-align: center;font-weight: 600;font-size: 18px;">KHOA HỆ THỐNG THÔNG TIN </p>
				</div>
			</div>
		<div id="contentCol" class="hasRightCol">
			<div id="contentArea">
				<div class="statistic-table">
					<table class="table-test">
						<tr>
							<th colspan="2" style="text-align: center; font-weight: 600;">
								Thống kê tài khoản người dùng hệ thống 
							</th>
						</tr>
						<tr>
							<th colspan="2" style="text-align: left;">Ngày thống kê: <?php echo date("d-m-Y G:i")?> 
							</th>
						</tr>
						<tr>
							<th colspan="5" style="text-align: left;">Người thống kê: <?php
									$auth = Zend_Auth::getInstance();
									if ($auth->hasIdentity())
							  			$userhaslogin = $auth->getStorage()->read();  		
									echo $userhaslogin->firstname." ".$userhaslogin->lastname;	
									?>
							</th>
						</tr>
						<tr>
							<th colspan="5" class="head-title-th">Có <?php echo $this->dataStatistic['totalUser'];?> tài khoản thuộc <?php echo $this->dataStatistic['total'];?> nhóm người dùng hệ thống
							</th>
						</tr>
						<tr>
							<td colspan="5"><hr/></td>
						</tr>
						<tr>
							<td colspan="5">	
								<ul>
									<?php if (count($this->dataStatistic['GroupUser'])>0)
										foreach($this->dataStatistic['GroupUser'] as $keyGroup=>$groupUserItem){		
									?>
									<li><?php echo ($keyGroup+1).". Nhóm ".$groupUserItem['ObjOneGroupUser']['group_name']; ?> </li>
									<?php } ?>
								</ul>
							</td>
						</tr>
						<tr>
							<td colspan="5"><hr/></td>
						</tr>
						<?php if (count($this->dataStatistic['GroupUser'])>0){ ?>
						<tr>
							<th>Nhóm người dùng</th>
							<th>Số tài khoản</th>
						</tr>
						<?php foreach($this->dataStatistic['GroupUser'] as $keyGroup1=>$groupUserItem1){ ?>		
						<tr>
							<td>
								Người dùng <?php echo $groupUserItem1['ObjOneGroupUser']['group_name'];?>:
							</td>
							<td>
								<?php echo $groupUserItem1['CountOneGroupUser'];?> tài khoản
							</td>
						</tr>
						<?php } } ?>

					</table>
				</div>
			</div>
		</div>
	</div>
</div>
